PhucLHSE/DakLakCoffeeSupplyChain_BE

Database/DakLakCoffee_SCM.sql
This pull request seeds initial sample data for core user types in the DakLak Coffee Supply Chain system. The SQL inserts are designed for testing and early development of authentication, authorization, and entity relationships.
---
- 6 system roles added:
- `Admin`
- `BusinessManager`
- `BusinessStaff`
- `Farmer`
- `AgriculturalExpert`
- `DeliveryStaff`
- 4 mock users inserted with realistic role mapping:
- `Admin`: **Phạm Huỳnh Xuân Đăng**
- `BusinessManager`: **Lê Hoàng Phúc**
- `Farmer`: **Nguyễn Nhật Minh**
- `AgriculturalExpert`: **Lê Hoàng Thiên Vũ**
- Linked to `BusinessManager` user with full company info: **Công ty Cà Phê DakLak**
- Linked to `Farmer` user with farm location, size, and **VietGAP** certification.
- Linked to `Expert` user with coffee disease expertise, academic …
=> feat(seed): add sample user data for Roles, Accounts, Managers, Farmers, and Experts

Database/DakLakCoffee_SCM.sql, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/BusinessManager.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/BusinessStaff.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/WarehouseInboundRequest.cs
- 🔁 Renamed `BusinessManagerID` ➜ `BusinessStaffID` in `WarehouseInboundRequests` table
- 🔒 Updated foreign key constraint to reference `BusinessStaffs(StaffID)`
- 🆕 Added `DEFAULT NEWID()` to `InboundRequestID` (primary key)
- ♻️ Regenerated EF Core models to reflect schema updates
---
- `BusinessStaffID` is a more accurate reflection of the actual business actor handling the request
- Adding `DEFAULT NEWID()` improves consistency and simplifies record creation
- Keeps database schema and backend models in sync for reliable development
---
- Affects `WarehouseInboundRequests` table and related EF Core models
- May require re-seeding or migration if deployed to staging/production
- No major logic change, but schema references must be reviewed in services/controllers
---
- Database Schema …
=> refactor(database): rename BusinessManagerID to BusinessStaffID and add default NEWID() to primary keys

Database/DakLakCoffee_SCM.sql
This PR seeds initial data for the Crop Monitoring module, including:
- `CropSeasons`: One crop season linked to REG-2025-0001 and FRM-2025-0001
- `CropSeasonDetails`: Arabica coffee detail with yield and harvest period
- `CropStages`: Standardized 5-stage crop lifecycle (planting → harvesting)
- `CropProgresses`: First progress record for "planting" stage with note
---
- Enable full Luồng 2: Nông dân tạo mùa vụ, cập nhật tiến độ gieo trồng
- Support frontend dev with realistic data for UI testing
- Prepare for timeline tracking and expert feedback features
---
- `CropSeasons`
- `CropSeasonDetails`
- `CropStages`
- `CropProgresses`
---
- ✔️ Fully linked via foreign keys (Farmer, CoffeeType, Registration, Commitment)
- ✔️ Progress inserted with `StageCode = 'planting'` and custom note
=> feat(seed): insert initial data for CropSeasons, CropSeasonDetails, CropStages, and CropProgresses

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs
Refactored `DeleteAsync` logic in `UserAccountService` and `ProductService`:
- Changed return type from `Task<bool>` ➜ `Task<int>`
- Updated condition check from `if (result == Const.SUCCESS_DELETE_CODE)` ➜ `if (result > 0)`
---
- Aligns with EF Core's `SaveChangesAsync()` which returns the number of affected rows
- Allows for better control and error handling based on how many entities are actually deleted
- Makes the code more consistent across create/update/delete operations
---
- `UserAccountService`
- `ProductService`
=> refactor(service): change delete result to Task<int> in UserAccount and Product services

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonDeleteDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/UserAccountDTOs/UserAccountDeleteDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICropSeasonRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CropSeasonRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropSeasonService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
- Implemented DeleteById in CropSeasonService that:
- Validates if the CropSeason exists
- Deletes all related CropSeasonDetails
- Removes the CropSeason entity
- Fixed return type mismatch in DeleteById to match ICropSeasonService interface
- No mapping needed for DeleteDto as only CropSeasonId is used
=> Add Delete functionality for CropSeason with related CropSeasonDetails

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodDTOs/ProcessingMethodDeleteDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodDTOs/ProcessingMethodDetailDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodDTOs/ProcessingMethodViewAllDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingMethodMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs
This commit reorganizes the DTO structure by moving the `ProcessingMethod`-related DTOs (`Create`, `Update`, `Detail`) from the nested `Flow3DTOs` folder into the root `DTOs` directory for improved maintainability and separation of concerns.
---
- **Moved Files:**
- `ProcessingMethodCreateDto.cs`
- `ProcessingMethodUpdateDto.cs`
- `ProcessingMethodDetailDto.cs`  
➤ From: `Common/DTOs/Flow3DTOs/`  
➤ To: `Common/DTOs/`
- **Updated Namespaces & `using` Directives**  
All references to the above DTOs have been updated to reflect their new locations.
- **Added New Field:**
- `Author` (type: `string`)  
→ Added to:
- `ProcessingMethodCreateDto`
- `ProcessingMethodDetailDto`
---
- `APIService/Controllers/ProcessingMethodController.cs`
- `Services/Services/ProcessingMethodService.cs`
- …
=> refactor(dto): move ProcessingMethod DTO to root and add Author field

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessManagerDTOs/BusinessManagerCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IBusinessManagerRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/BusinessManagerRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBussinessManagerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessManagerMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs
This Pull Request implements the **Create BusinessManager API**, including full 3-layer architecture (Controller → Service → Repository). It allows admin users to register new business managers into the system.
---
- Add `BusinessManagerCreateDto` with full validation annotations.
- Implement logic in `BusinessManagerService.Create()`:
- Validate user existence, role, and soft-deletion.
- Check for duplicate BusinessManager by `UserId`.
- Check for existing company using `TaxId`.
- Generate a unique `ManagerCode` using the current year and auto-incremented index.
- Return enriched response including:
- `Email`, `FullName`, `PhoneNumber` from `UserAccount`.
- Add `CodeGenerator` class for user code creation (replace old `UserCodeGenerator`).
- Update `BusinessManagerRepository` and …
=> feat(business-manager): implement create API with validation, code gen, and 3-layer structure

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodDTOs/ProcessingMethodCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingMethodService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingMethodMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs
This commit introduces the full implementation for creating a `ProcessingMethod`, following the Clean Architecture structure.
- `CreateProcessingMethodDto`: DTO for input validation
- `CreateProcessingMethodValidator`: Ensures valid method name and structure
- `ProcessingMethodMapper`: Maps DTO to entity
- `ProcessingMethodService.CreateAsync`: Handles the business logic for:
- Generating `MethodCode` based on BusinessManager’s company name
- Validating BStaff's relation to BusinessManager
- Calling repository to persist the entity
- Returning proper `ServiceResult` responses
- `Application.DTOs.ProcessingMethodDTOs`
- `Application.Validators.ProcessingMethod`
- `Application.Services.ProcessingMethodService`
- `Infrastructure.Repositories` (if applicable)
- Entity and DbContext mapping …
=> feat(processing-method): implement create ProcessingMethod logic

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessManagerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs
This PR implements the `DELETE` API for the `BusinessManager` module, including full service integration, controller endpoint, and robust error handling.
---
- Add `DeleteByIdAsync` method in `BusinessManagersController`
- Implement `DeleteById` logic in `IBusinessManagerService` and its implementation
- Handle 404 (not found), 409 (conflict), and 500 (internal server error) cases
- Ensure consistency with the existing soft delete logic
- Add Vietnamese response messages for localization
---
---
Only users with the `Admin` role are allowed to perform this action.
---
```http
DELETE /api/BusinessManagers/{managerId}
Response:
- 200 OK: Xóa thành công.
- 404 Not Found: Không tìm thấy quản lý doanh nghiệp.
- 409 Conflict: Xóa thất bại.
=> feat(business-manager): implement delete API with service, controller, and error handling

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessManagerMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/RoleService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs
This PR applies unified handling of Vietnam time zone (UTC+7) for `CreatedAt` and `UpdatedAt` fields in entity lifecycle operations across the system.
---
- Updated mappers to use `DateHelper.NowVietnamTime()`:
- `BusinessManagerMapper` (create only)
- `RoleMapper` (create & update)
- `UserAccountMapper` (create & update)
- Updated soft delete logic to record `UpdatedAt` in Vietnam time for:
- `BusinessManagerService`
- `RoleService`
- `UserAccountService`
- `ProductService`
---
- `BusinessManagerMapper.cs`
- `RoleMapper.cs`
- `UserAccountMapper.cs`
- `BusinessManagerService.cs`
- `RoleService.cs`
- `UserAccountService.cs`
---
- Uses Windows timezone ID: `"SE Asia Standard Time"`
- Timestamp updates now reflect local business context (Vietnam)
- Future support for …
=> feat(timezone): apply Vietnam time (UTC+7) to create/update mappers and soft delete services

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICropSeasonRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CropSeasonRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropSeasonService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
Implemented soft delete for the `CropSeason` module using `IsDeleted` flag.
---
- Added `IsDeleted` property to `CropSeason` entity
- Updated `CropSeasonRepository`:
- `GetAllCropSeasonsAsync`, `GetById`, `GetWithDetailsById` now exclude soft-deleted records
- Added `SoftDelete()` method
- Extended `ICropSeasonRepository` with `SoftDelete(CropSeason entity)`
- Implemented `SoftDeleteAsync(Guid)` in `CropSeasonService`
- Declared `SoftDeleteAsync` in `ICropSeasonService`
- Created PATCH endpoint:
=> feat(cropseason): implement soft delete logic and endpoint

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessBuyerDTOs/BusinessBuyerDeleteDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
This PR implements the soft delete functionality for `BusinessBuyer` with proper service-layer logic, API controller integration, and data filtering in retrieval methods.
---
- Added `SoftDeleteById(Guid buyerId)` method in `BusinessBuyerService`
- Updated `IBusinessBuyerService` interface with new soft delete definition
- Created a new API endpoint in `BusinessBuyersController`:
- `PATCH api/businessbuyers/soft-delete/{buyerId}`
- Ensured soft-deleted records are excluded in `GetAll()` via `IsDeleted != true`
- Introduced `BusinessBuyerDeleteDto.cs` for potential future extensibility
---
- Soft delete endpoint tested via Swagger/Postman
- `GetAll` API successfully excludes soft-deleted records
- All service logic wrapped with error handling and return codes (404, 409, 500)
---
- All …
=> feat(business-buyer): implement soft delete API with service, controller, and filtering in GetAll

Database/DakLakCoffee_SCM.sql, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessBuyerDTOs/BusinessBuyerUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessBuyerMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
This PR introduces the full implementation of the **Update API for BusinessBuyer**, including validation, duplication checks, DTO mapping, and service/controller integration.
---
- Added `BusinessBuyerUpdateDto` with full annotation-based validation
- Implemented `Update` method in `BusinessBuyerService` with:
- Business rule to ensure `TaxId` uniqueness per creator (`CreatedBy`)
- Mapping logic from `UpdateDto` to existing entity
- Vietnam time update on `UpdatedAt`
- Updated `BusinessBuyerMapper` to support `.MapToExistingBusinessBuyer(...)`
- Updated controller endpoint to support `PUT` with `BuyerId` from DTO
- Synced database model if needed (`.sql` file)
---
- `BusinessBuyerUpdateDto.cs`
- `BusinessBuyerMapper.cs`
- …
=> feat(business-buyer): implement update API with validation, duplicate TaxId check, and DTO mapping

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CoffeeTypeController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcurementPlansController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICoffeeTypeService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CoffeeTypeService.cs
This pull request implements both **soft delete** and **hard delete** functionalities for coffee types, identified by their unique ID.
- Endpoint: `DELETE /api/coffee-types/{id}`
- Supports query parameter `?force=true` for **hard delete**
- Soft delete: Marks the coffee type as inactive or deleted without removing it from the database
- Hard delete: Permanently removes the record from the database
- Default behavior is soft delete (`force=false`)
- Returns:
- `200 OK` on successful deletion
- `404 Not Found` if the coffee type does not exist
- `400 Bad Request` for invalid parameters
- Unit tests for delete service logic
- Integration tests for:
- Soft delete
- Hard delete
- Invalid or nonexistent ID cases
---
This implementation helps preserve historical data with soft delete while …
=> feat(CofeeType) Hard delete and soft delete by id coffee type API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingStageController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodStageDTOs/CreateProcessingStageDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingStageRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingStageRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingStageService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingStageMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingStageService.cs
- Implemented `CreateAsync()` for `ProcessingStage`
- Returned full `ProcessingStageViewDetailDto` after creation
- Included `MethodName`, `MethodCode`, and audit fields in the response
- Added `CreateAsync` method in `ProcessingStageService`
- Updated `IProcessingStageRepository` and `ProcessingStageRepository` to support creation
- Fixed missing `GetStageByIdAsync` or used `GetByIdAsync` with custom query including navigation
```json
{
"stageId": 26,
"stageCode": "drying",
"stageName": "Phơi nắng",
"methodId": 1,
"methodName": "Sơ chế khô (Natural)",
"createdAt": "2025-06-22T13:00:00Z",
...
}
=> feat(processing-stage): implement create stage with detail response

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonDetailDTOs/CropSeasonDetailViewDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonViewDetailsDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CropSeasonRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropSeasonMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
feat: update CropSeason GetById to include and display details
- Modified CropSeasonViewDetailsDto to include a list of CropSeasonDetails
- Added mapping of CropSeasonDetails to DTO, including Area and CoffeeTypeName
- Updated repository method to include CropSeasonDetails and CoffeeType
- Now GET /api/CropSeasons/{id} returns full detail information per season
=> feat: show CropSeasonDetails in CropSeason GetById response

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractDeleteDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IContractItemRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ContractItemRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
This pull request enhances the `Contract` module by implementing **soft delete with cascading** to related `ContractItems`. It also ensures both `GetAll` and `GetById` APIs return only active (non-deleted) contracts and items.
---
- **Soft delete logic**:
- When a contract is soft-deleted, all its associated `ContractItems` are also marked `IsDeleted = true`.
- Ensures data consistency and avoids orphaned items in contract detail view.
- **Filtering enhancement**:
- `GetAll()` now excludes contracts where `IsDeleted = true`.
- `GetById()` view excludes soft-deleted contracts and does **not** return `ContractItems` marked as deleted.
---
- `ContractService.cs`: 
- Updated `SoftDeleteContractById()` to cascade delete to items.
- Applied `IsDeleted` filtering in `GetAll()` and `GetById()`.
- …
=> feat(contract): implement soft delete with cascade on related contract items

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
☕ Feature: Hard Delete ContractItem API + Fix Create Response + Sort ContractItems in GetById
📌 Objective  
Implement hard delete API for `ContractItem`, fix potential null reference in create response, and sort `ContractItems` by code when viewing contract detail.
---
✅ Key Changes  
This PR includes:
- **DELETE /api/contractitems/{id}**: Implemented hard delete for ContractItem
- **POST /api/contractitems**:
- Handled potential `null` in `responseDto` to avoid null reference warning
- Prevent duplicated coffee type in same contract
- **GET /api/contracts/{id}**:
- Sort `ContractItems` by `ContractItemCode` (ascending) before mapping to DTO
---
✨ Improvements  
- Response from create API is now null-safe
- Contract detail view is easier to read with ordered `ContractItems`
---
📂 Affected …
=> feat(contract-item): implement delete API, sort ContractItems by code in GetById, and ensure null-safe response in create

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingParameterRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingParameterRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingParameterService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingParameterService.cs
Thêm API `DELETE /api/processingparameter/hard/{parameterId}` để **xóa vĩnh viễn thông số** trong quá trình chế biến (ProcessingParameter). Khác với soft delete, bản ghi sẽ bị xóa khỏi cơ sở dữ liệu.
---
- Thêm `HardDeleteAsync(Guid)` trong `Repository` & `Service`
- Controller thêm endpoint `DELETE /hard/{id}`
- Không set `IsDeleted` mà xóa trực tiếp khỏi DB
- Trả kết quả thành công hoặc thông báo không tìm thấy
---
- `ProcessingParameterController.cs`
- `ProcessingParameterService.cs`
- `IProcessingParameterService.cs`
- `ProcessingParameterRepository.cs`
- `IProcessingParameterRepository.cs`
---
- API: `DELETE /api/processingparameter/hard/{parameterId}`
---
1. Gửi request:DELETE /api/processingparameter/hard/{guid-id}
2. Kiểm tra:
- Trả về 200 nếu xoá thành công
- Gọi lại `GET` thì …
=> [ProcessingParameter] Add Hard Delete API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
Implement a hard delete feature for `Contract`, ensuring all associated `ContractItems` are also removed from the database. This applies to the `BusinessManager` role and impacts the contract deletion flow in the supply chain management system.
---
- Implemented `DeleteContractById` in `ContractService` with manual deletion of linked `ContractItems`
- Updated `ContractsController` to expose new DELETE endpoint with proper role authorization
- Ensured `ContractItems` are loaded with the contract entity and removed before deleting the contract itself
---
- `IContractService.cs`
---
- *(None)* – logic added to existing service and controller files
---
1. **Login** as a `BusinessManager` to obtain a valid JWT token  
2. Send DELETE request to …
=> feat(contract): implement hard delete with cascade removal of related contract items

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryItem/ContractDeliveryItemUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IContractDeliveryItemRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ContractDeliveryItemRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryItemMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs
Implement an API to update a `ContractDeliveryItem` with full validation and business rule enforcement. This supports `BusinessManager` and `BusinessStaff` roles in adjusting planned delivery quantities, notes, or coffee type as needed.
---
- Added `ContractDeliveryItemUpdateDto` with `IValidatableObject` for quantity > 0.
- Implemented `Update` method in `ContractDeliveryItemService` with:
- validation for ownership between `DeliveryBatch` and `ContractItem`
- duplication check in the same batch
- planned quantity overflow prevention
- Added `MapToUpdateContractDeliveryItem` in Mapper
- Updated `ContractDeliveryItemRepository` with `SumPlannedQuantityAsync(..., excludeId)`
- Controller method `PUT /api/ContractDeliveryItems/{id}` added with ID consistency check
---
- …
=> feat(contract-delivery-item): implement update API with validation, business rules, and mapper integration

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/AuthController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AuthDTOs/ResendEmailVerificationRequestDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IAuthService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/AuthService.cs
This pull request introduces a new API endpoint that allows users to request a resend of their email verification link. This feature helps users who did not receive the initial verification email or whose verification link expired.
---
- **HTTP Method:** `POST`
- **Route:** `/api/auth/resend-verification`
- **Request Body:**
- `email` (string): User’s registered email address
- **Response:**
- **200 OK**: Email resent successfully
- **400 Bad Request**: Invalid or already verified email
- **404 Not Found**: Email not found in system
---
- Added new controller endpoint under `AuthController`
- Validated email existence and verification status before sending
- Integrated with existing email service to generate and send verification link
- Included logging for tracking resend attempts
- …
=> feat(Auth) Implement Resend email verification API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs
---
Update the `GetAll` API in `ProcessingBatch` to support:
- 👩‍💼 **Admin**: can view all processing batches in the system
- 👨‍🌾 **Farmer**: can only view their own batches (filtered by `farmerId` derived from `userId` in the token)
---
- Added `isAdmin` parameter to `GetAllByUserId(Guid userId, bool isAdmin = false)`
- If `isAdmin == true`, fetch all non-deleted `ProcessingBatch` records
- If `isAdmin == false`, map `userId → farmerId` and filter batches accordingly
- Updated controller to detect role using `User.IsInRole("Admin")`
---
- `ProcessingBatchController.cs`
- `IProcessingBatchService.cs`
---
---
- Ensure frontend includes valid JWT token with `userId` claim
- Future enhancements could include pagination, status filtering, or crop season filtering
=> feat(processing-batch): support role-based access for viewing batches (Admin/Farmer)

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessManagerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs
Enforce role-based access control in the **Soft Delete BusinessManager API**, allowing only `Admin` to delete any manager and restricting `BusinessManager` to soft-delete only themselves.
---
- Refactor `SoftDeleteById` service to include `userId` and `userRole` parameters
- Implement self-access validation logic for `BusinessManager` role
- Enhance response clarity with consistent status handling for deleted/nonexistent records
---
- `BusinessManagersController.cs`
- `IBusinessManagerService.cs`
- `BusinessManagerService.cs`
---
---
1. **Login** with a valid JWT token for a user with `BusinessManager` or `Admin` role
2. Send a `PATCH` request to:
- `PATCH /api/businessmanagers/soft-delete/{managerId}`
3. Ensure:
- `Admin` …
=> refactor(business-manager): enforce role-based access in SoftDelete API with self-check for BusinessManager

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
Enhance the `GetById` API of BusinessBuyer by enforcing ownership validation. This ensures that only the BusinessManager who created the buyer can retrieve its details, preventing unauthorized access across different businesses.
---
- Refactored `GetById` in `BusinessBuyerService` to verify the buyer belongs to the current BusinessManager via `CreatedBy == ManagerId`.
- Applied `IsDeleted != true` checks for both BusinessManager and BusinessBuyer entities.
- Updated controller to extract `userId` from token and pass it to the service layer.
- Added `BusinessBuyerExistsAsync(...)` in controller to encapsulate access control and existence check logic.
---
- `IBusinessBuyerService.cs`
---
1. **Login** as a BusinessManager to obtain …
=> refactor(business-buyer): enforce access control in GetById API to ensure buyer belongs to current BusinessManager

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmingCommitmentController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IFarmingCommitmentService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs
This pull request introduces a new API endpoint that allows the currently signed-in farmer to retrieve all of their own farming commitments. This helps ensure personalized data access, enhances data privacy, and provides the basis for farmer-specific views in the frontend.
---
- **HTTP Method:** `GET`
- **Route:** `/api/farmers/commitments`
- **Authentication:** Required (farmer must be logged in)
- **Response:**
- **200 OK**: Returns a list of farming commitments belonging to the authenticated farmer
- **401 Unauthorized**: If user is not authenticated
- **Empty List**: If the farmer has no commitments yet
Each commitment object may include:
- Commitment ID
- Crop type and variety
- Quantity or area committed
- Start and end dates
- Status or fulfillment progress
---
- Used …
=> feat(FarmingCommitment) Implement get all farming commitment for signed in farmer API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UserAccountsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IUserAccountService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs
Refactor the `GetAll` API in `UserAccountService` to enforce **role-based access control**, allowing:
- `Admin` to retrieve all users.
- `BusinessManager` to retrieve only staff under their supervision.
---
- Refactored `GetAll` method in `UserAccountService` to conditionally filter by role.
- Integrated `SupervisorId` check for `BusinessManager` access logic.
- Injected `userId` and `userRole` from claims in `UserAccountsController`.
- Improved clarity and separation of responsibilities between Admin and Manager access paths.
- Added safeguard at service level to prevent misuse from external calls.
---
- `UserAccountsController.cs`
- `UserAccountService.cs`
- `IUserAccountService.cs`
---
- _N/A_ (no new files introduced)
---
1. **Login** with an `Admin` or `BusinessManager` account to …
=> refactor(user-account): enforce role-based access in GetAll API for Admin and BusinessManager

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrdersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Enhance the `GetById` API for Orders to enforce role-based access control. Ensures that only the owning `BusinessManager` or their assigned `BusinessStaff` can view the details of an order that belongs to them.
---
- Refactored `GetById(Guid orderId)` to `GetById(Guid orderId, Guid userId)` in `OrderService`
- Added logic to resolve `managerId` from `userId` for both `BusinessManager` and `BusinessStaff`
- Updated predicate to restrict access to orders belonging to the current manager
- Adjusted `OrdersController` to extract `userId` from token via `ClaimsHelper`
- Synchronized logic with `GetAll` for consistency in access control
---
- `IOrderService.cs`
---
- _N/A_
---
1. **Login** as `BusinessManager` or `BusinessStaff`
2. Send request to …
=> refactor(order): enforce role-based access in GetById API for BusinessManager and Staff

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UserAccountsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IUserAccountService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs
Refactor the Create UserAccount API to enforce **role-based restrictions**:  
- `Admin` can create accounts with any role.  
- `BusinessManager` can only create `BusinessStaff` accounts assigned to their company.
---
- Refactored `CreateUserAccountAsync` in `UserAccountsController` to extract `userId` and `userRole` from token.
- Updated `IUserAccountService.Create()` to accept `userId` and `userRole` for permission validation.
- Enforced role-based creation logic:
- Only Admin and BusinessManager can create.
- BusinessManager can **only** create BusinessStaff.
- Retained validation for:
- Email/phone uniqueness
- Age requirement (via system config)
- Role existence check
- Returned consistent messages for permission errors or invalid requests.
---
- `UserAccountsController.cs`
- …
=> refactor(user-account): enforce role-based create logic for Admin and BusinessManager

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UserAccountsController.cs
Enhance the existing `UpdateUserAccount` API to include strict role-based access control.  
Ensure only authorized users (e.g., Admin, BusinessManager, or self) can update a given user, based on claims from JWT token.
---
- Implemented `UpdateUserAccountAsync` in `UserAccountsController` with `GetUserId()` and `GetRole()` from claims
- Added permission check via `_userAccountService.CanAccessUser(...)`
- Improved HTTP response handling with proper 403, 404, 409, and 500 statuses
---
- `UserAccountsController.cs`
---
- N/A
---
1. **Login** using a valid user with different roles (e.g., `Admin`, `BusinessManager`, `Farmer`)
2. Send request to endpoint:
- `PUT /api/useraccounts/{userId}`
3. Sample request body:
```json
{
"UserId": …
```
=> refactor(user-account): enforce role-based access in Update API with claims check and CanAccessUser validation

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IFarmingCommitmentRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/FarmingCommitmentRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropSeasonMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
feat(api): create crop season based on valid farming commitment
- Updated CropSeasonController to accept commitmentId when creating crop season
- Extended CropSeasonCreateDto with commitmentId field for input binding
- Implemented validation logic in CropSeasonService:
- Only allow creating crop season if the given commitment belongs to current farmer
- Only allow if the commitment has not been used and is in APPROVED status
- Updated CropSeasonMapper to map data from commitment (e.g. quantity, area, farmer info) when creating a new crop season
- Added HasValidCommitmentForCropSeasonAsync method to IFarmingCommitmentRepository and implemented it
- Cleaned up error messages to return proper 403 or 400 when invalid commitment
=> feat(api): create crop season based on valid farming commitment

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropSeasonMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
feat(api): support crop season update with commitmentId validation
- Cho phép cập nhật thông tin mùa vụ bao gồm: seasonName, commitmentId, area, startDate, endDate, note, status
- Validate: không cho phép startDate >= endDate
- Validate: không cho phép duplicate mùa vụ cùng RegistrationId trong cùng năm (ngoại trừ chính nó)
- Phân quyền: chỉ cho phép Admin hoặc chủ sở hữu (Farmer) thực hiện cập nhật
- Cập nhật phương thức MapToExistingEntity để đồng bộ với DTO mới
- Thêm kiểm tra cropSeasonId khớp với route trong controller
=> feat(api): support crop season update with commitmentId validation

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
This PR refactors the **SoftDelete API for BusinessBuyer** to ensure that only the **BusinessManager who created the buyer** is authorized to soft delete it. It aligns with the security pattern applied in the hard delete and update APIs for consistent access control enforcement.
---
- Refactored `SoftDeleteBusinessBuyerByIdAsync` controller method to extract `userId` from token and pass to service
- Updated `IBusinessBuyerService` and `BusinessBuyerService` to require `userId` and validate ownership before soft deletion
- Enforced logic that the BusinessBuyer must belong to the currently authenticated BusinessManager
---
- `IBusinessBuyerService.cs`
---
- ❌ *(No new files added)*
---
1. **Login** with role `BusinessManager` to …
=> refactor(business-buyer): enforce access control in SoftDelete API to ensure buyer belongs to current BusinessManager

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingWasteController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWastesDTOs/ProcessingWasteViewAllDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchWasteRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchWasteRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingWasteService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchWasteMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingWasteService.cs
Implement the `GetAll` API for `ProcessingWaste`, allowing:
- **Admin**: to retrieve all waste records
- **Farmer**: to retrieve only wastes belonging to their own `Progress` entries
Goal: enforce role-based access control using `userId` and ensure correct data visibility based on roles.
---
- Created `ProcessingWasteViewAllDto` for response formatting
- Added `ProcessingWasteMapper` to map from entity to DTO
- Implemented `GetAllByUserIdAsync(Guid, bool)` service logic with role-based filtering
- Optimized queries via `UserAccountRepository` and `ProcessingBatchProgressRepository`
- Created `ProcessingWasteController` with `GET /api/ProcessingWaste` endpoint
---
- `ProcessingWasteService.cs`
- `ProcessingWasteController.cs`
- `IProcessingWasteService.cs`
- `IProcessingWasteRepository.cs` …
=> feat: implement GetAll ProcessingWaste with role-based access (Farmer/Admin)

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs
Refactor `DeleteProductById` API to enforce scoped deletion logic for `BusinessManager`. This ensures that managers can only delete products either created by themselves or by staff under their supervision.
---
- Refactored `ProductService.DeleteProductById` to include ownership and delegation checks
- Verified `CreatedBy` directly and validated staff-manager relationship via `SupervisorId`
- Cleaned up controller logic to pass `userId` from token
- Maintained role-based restriction via `[Authorize(Roles = "BusinessManager")]`
---
- `ProductsController.cs`
- `IProductService.cs`
---
- *(None)* — logic added inside existing service method
---
1. **Login** as a `BusinessManager` to obtain JWT token
2. Send request to endpoint:
- `DELETE /api/products/{productId}`
- …
=> refactor(product): enforce scoped deletion permission for BusinessManager in Delete API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs
Refactor the `DeleteContractItemById` API to enforce permission boundaries for `BusinessManager` role. Prevent unauthorized deletion of `ContractItem` records created by other users not under their supervision.
---
- Refactor service method `DeleteContractItemById` to include `userId` and check `BusinessManager` ownership
- Add DB-level validation to ensure only creator or authorized manager can perform deletion
- Improve error responses for clearer permission failure reasons
---
- `IContractItemService.cs`
---
- *(None)*
---
1. **Login** using a `BusinessManager` account to get a valid JWT token
2. Send request to:
- `DELETE /api/contractitems/{contractItemId}`
3. Ensure:
- You **can …
=> refactor(contract-item): enforce scoped deletion permission for BusinessManager in Delete API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs
Implement scoped permission for the `PATCH /api/contractdeliveryitems/soft-delete/{deliveryItemId}` API.  
Ensure that only `BusinessManager` users can perform soft-delete on delivery items that belong to their contracts (based on `SellerId` ownership).
---
- Refactored `SoftDeleteContractDeliveryItemById` service to validate `SellerId` matches current manager  
- Added permission control logic using `userId → ManagerId/SupervisorId → Contract.SellerId`  
- Updated controller to use proper status handling and consistent structure with Delete API  
---
- `ContractDeliveryItemsController.cs`
- `IContractDeliveryItemService.cs`
---
- *(No new files added)* – logic extended inside existing API and service.
---
1. **Login** using a `BusinessManager` account …
=> refactor(contract-delivery-item): enforce scoped soft-delete permission for BusinessManager in SoftDelete API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs
Add scoped permission control for the `Create` API of `ContractDeliveryItem`. Only `BusinessManager` or `BusinessStaff` (under a Manager) can create a delivery item if and only if the delivery batch belongs to their managed contract.
---
- Enforced access control in `Create` method to resolve `userId → managerId` → `Contract.SellerId`
- Integrated `DeliveryBatch` ownership validation into repository predicate
- Added `userId` parameter to `Create` service and controller layer
- Maintained full logic for validation: contract item match, planned quantity constraint, duplicate check, and response DTO mapping
---
- `ContractDeliveryItemsController.cs`
- `IContractDeliveryItemService.cs`
- `ContractDeliveryItemCreateDto.cs`
- `ContractDeliveryItemMapping.cs` …
=> refactor(contract-delivery-item): enforce scoped creation permission for BusinessManager and Staff in Create API

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchDetailsDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchViewDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/ProcessingEnums/ProcessingStatus.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs
Refactored the `ProcessingBatch` logic to store and return `Status` as an enum (`ProcessingStatus`) instead of a string for improved type safety and consistency.
- Updated `ProcessingBatch.Status` mapping to use `ProcessingStatus` enum
- Modified View DTOs (`ProcessingBatchViewDto`, `ProcessingBatchDetailsDto`) to reflect enum usage
- Adjusted mapper methods to parse enum properly and prevent runtime exceptions
- Ensured status enum value is sent to frontend as integer (int) instead of string
- Test `GetAll`, `GetById`, and `Update` endpoints of `ProcessingBatch`
- Confirm that the `status` field in responses is an integer (e.g., 0, 1, 2, 3)
- Ensure no errors occur when mapping or parsing the status value
- `ProcessingBatchViewDto.cs`
- `ProcessingBatchDetailsDto.cs`
- …
=> fix(processing-batch): switch Status field to enum type

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrderItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs
Refactor the `DeleteOrderItemById` service to enforce scoped deletion by validating the `userId` of the current `BusinessManager`. This enhances access control even though `CreatedBy` is not available in `OrderItem`.
---
- Updated `OrderItemService.DeleteOrderItemById()` to include `userId`-based validation via `BusinessManager` lookup
- Included `Order` and `ContractDeliveryItem` in `OrderItem` query for potential future scoped logic
- Cleaned up error handling and improved separation of concern in controller and service layers
---
- `OrderItemService.cs`
- `IOrderItemService.cs`
- `ProductService.cs` *(minor related adjustment)*
---
- *(None)*
---
1. **Login** as a `BusinessManager` and obtain a valid JWT token
2. Send DELETE request to:
- `DELETE …
=> refactor(order-item): enforce scoped deletion for BusinessManager by validating userId

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrderItemsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderItemService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderItemService.cs
Refactor `SoftDeleteOrderItemById` API to ensure that only the corresponding `BusinessManager` (identified via `userId` from JWT token) can soft-delete `OrderItem`, adding access control to protect business data and prevent unauthorized deletion.
---
- Added `userId` parameter to `SoftDeleteOrderItemById` service method
- Extracted `userId` from token in controller using `ClaimsHelper`
- Verified existence of `BusinessManager` before performing soft-delete
- Refactored logic to keep service clean and exception-safe
- Updated service interface and controller to match new method signature
---
- `IOrderItemService.cs`
- `OrderItemService.cs`
---
- *(None)*
---
1. **Login** as a user with `BusinessManager` role to obtain JWT token
2. Send a request to the …
=> refactor(order-item): enforce scoped soft-delete for BusinessManager with userId verification

Database/DakLakCoffee_SCM.sql, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/CultivationRegistration.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/FarmingCommitment.cs
- Fix the relationship between `FarmingCommitments` and `CultivationRegistration` in the database context.
- Establish proper foreign key constraints to ensure referential integrity between the two entities.
- Update DBContext configurations to correctly map the associations.
- Improve data consistency and accuracy for cultivation registrations linked to farming commitments.
- Prevent potential issues arising from missing or incorrect relational mappings in database operations.
=> refactor(SQL, DBContext) Fix FarmingCommitments and CultivationRegistration relations

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrdersController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Refactor the existing soft-delete logic for `Order` to enforce proper permission checks. This ensures that only `BusinessManager` users can soft-delete orders that belong to them (via associated `Contract.SellerId`).
---
- Added `userId` validation via token in `SoftDeleteOrderByIdAsync` endpoint.
- Checked whether the user is a valid `BusinessManager` before processing deletion.
- Queried related `DeliveryBatch → Contract → SellerId` to enforce ownership.
- Marked both `Order` and its `OrderItems` as soft-deleted (`IsDeleted = true`).
- Updated timestamps and ensured changes are tracked properly by EF Core.
---
- `IOrderService.cs`
---
- _(No new files added in this PR)_
---
1. **Login** using a valid `BusinessManager` account to obtain JWT …
=> refactor(order): enforce scoped soft-delete permission for BusinessManager with seller validation

Database/DakLakCoffee_SCM.sql
This PR enriches the seed SQL script by adding a second `BusinessManager` along with associated `BusinessStaff`, `Farmers`, `Expert`, and `Warehouses`. The goal is to simulate a multi-enterprise environment in the supply chain system and validate role-based access flows across different organizational units.
---
- Insert new `UserAccounts` for roles: BusinessManager (2nd), 3 BusinessStaff, 4 Farmers, 1 Expert, 1 DeliveryStaff.
- Insert corresponding entries into:
- `BusinessManagers`
- `Farmers`
- `AgriculturalExperts`
- `BusinessStaffs`
- `Warehouses`
- Fix inconsistent warehouse codes and remove Lâm Đồng references (replaced with Đắk Lắk locations like Ea Kar, Krông Năng).
---
---
- Sample records for:
- ManagerCode `BM-2025-0002`
- StaffCodes …
=> feat(seed): add sample data for BusinessManagers, Farmers, Experts, Staffs, and Warehouses in SQL script

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs
Implement hard-delete functionality for Shipment and its related ShipmentDetails.  
This feature enables `BusinessManager` to permanently remove a shipment and all its nested shipment details via API.
---
- Implemented `DeleteShipmentById(Guid shipmentId)` in `ShipmentService`
- Removed related `ShipmentDetails` before deleting `Shipment`
- Integrated with `IShipmentService` and `ShipmentsController`
- Added proper result handling via `ServiceResult` and status codes
- Applied `[Authorize(Roles = "BusinessManager")]` at controller level
---
---
- ❌ _No new files were added in this commit_
---
1. **Login** with a BusinessManager account and retrieve JWT token
2. Send DELETE request:
- `DELETE …
=> feat(shipment): implement hard-delete API for Shipment and its details with validation and result handling

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentDetailsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentDetailService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentDetailService.cs
Refactor `DeleteShipmentDetailById` API to enforce scoped hard-delete by verifying that the `BusinessManager` owns the associated `Seller`. This prevents unauthorized deletion from other businesses.
---
- Refactored `ShipmentDetailService.DeleteShipmentDetailById` to validate `SellerId` against the current `BusinessManager`
- Modified controller endpoint `DELETE /api/shipmentdetails/{id}` to pass `userId` from JWT claims
- Ensured navigation includes necessary relations (Contract → DeliveryBatch → Order → ShipmentDetail)
- Role-based enforcement: only `BusinessManager` can delete
---
---
- _No new files added_
---
1. **Login** with role `BusinessManager` to get a JWT token
2. Send DELETE request …
=> refactor(shipment-detail): enforce scoped hard-delete by verifying manager's ownership via sellerId

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs
Refactor the existing soft-delete logic of `Shipment` to enforce role-based access control.  
Only the **BusinessManager** who owns the shipment (via `SellerId`) is allowed to perform the deletion.  
Also ensures related `ShipmentDetails` are soft-deleted accordingly.
---
- Refactored `SoftDeleteShipmentById` service method to validate `BusinessManager` by `UserId` and `SellerId`
- Soft-deleted all related `ShipmentDetails` alongside the parent shipment
- Added role-based endpoint in `ShipmentsController` restricted to `BusinessManager`
---
- `Controllers/ShipmentsController.cs`
- `Services/ShipmentService.cs`
- `Services/IShipmentService.cs`
---
---
1. **Login** using a BusinessManager account to get a valid **JWT token**
2. **Send request** to the endpoint:
- …
=> refactor(shipment): scoped soft-delete with SellerId check and related detail cleanup

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IGeneralFarmerReportRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/GeneralFarmerReportRepository.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ExpertAdviceService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/GeneralFarmerReportService.cs
Tự động cập nhật trạng thái `IsResolved` và `ResolvedAt` trong `GeneralFarmerReport` khi chuyên gia gửi phản hồi. Chức năng này thuộc luồng xử lý sự cố mùa vụ từ vai trò `AgriculturalExpert`.
---
- Bổ sung `Update()` vào `IGeneralFarmerReportRepository` và implement trong repository
- Từ `ExpertAdviceService`, sau khi tạo phản hồi sẽ gọi cập nhật trạng thái báo cáo tương ứng
- Sửa `GeneralFarmerReportService` để chuẩn hóa cập nhật
- Cleanup code & tránh lỗi repository không có `Update()`
---
- `IGeneralFarmerReportRepository.cs`
- `GeneralFarmerReportRepository.cs`
- `ExpertAdviceService.cs`
- `GeneralFarmerReportService.cs`
---
- (Không có file mới, chỉ cập nhật logic trong các service/repo hiện tại)
---
1. **Đăng nhập** với tài khoản role `AgriculturalExpert`
2. Gửi POST request tới …
=> feat(report): auto-resolve report when expert submits advice

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs
- Fix the Get All Available Plans API in the Procurement Plan module to ensure it also returns deleted plans.
- Update the query logic to include records marked as deleted without excluding them by default.
- Add a flag or parameter if needed to differentiate active plans from deleted ones in the response.
- Ensure proper handling and representation of deleted plans in the API response.
- Enhance validation and error handling to maintain robustness of the API.
- Maintain backward compatibility with existing clients while applying this change.
- Improve maintainability by cleaning up related data retrieval and filtering code.
=> refactor(procurement plan) Fix Get all available plans API also show deleted plans

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryBatchViewAllDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryBatchMapper.cs
Expose `contractNumber` in `ContractDeliveryBatchViewAllDto` to allow the frontend to display the associated contract number in the delivery batch listing screen (📦 Lịch giao hàng).  
Supports `BusinessManager` role viewing batches in a more readable UI without relying on internal contractId.
---
- Add `ContractNumber` property to `ContractDeliveryBatchViewAllDto`
- Map `ContractNumber` from `Contract` entity inside `ContractDeliveryBatchMapper`
- Ensure inclusion of related `Contract` when querying batches (if applicable)
---
- `ContractDeliveryBatchViewAllDto.cs`
- `ContractDeliveryBatchMapper.cs`
---
---
1. **Login** as `BusinessManager` to obtain a JWT token
2. Access the endpoint:
- `GET /api/contractdeliverybatches` …
=> feat(delivery-batch): expose contractNumber in ViewAllDto for FE display

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemViewDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderViewDetailsDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderItemMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Enable FE to retrieve and display correct `ContractDeliveryBatchId` and `ContractDeliveryItemId` when editing an `OrderItem`, ensuring users see accurate delivery batch/item data during order updates.
---
- Added `ContractDeliveryBatchId` and `ContractDeliveryItemId` fields to `OrderItemViewDto` and `OrderViewDetailsDto`.
- Updated `OrderItemMapper` and `OrderMapper` to map new fields from entity to DTO.
- Modified `OrderService.GetById` to `ThenInclude` `ContractDeliveryItem` for correct data population.
---
- `OrderItemViewDto.cs`
- `OrderViewDetailsDto.cs`
- `OrderItemMapper.cs`
- `OrderMapper.cs`
---
- N/A
---
1. **Login** with a `BusinessManager` or `BusinessStaff` account to obtain JWT token.
2. Send request:
- `GET /api/orders/{orderId}`
- Header: …
=> feat(order): include ContractDeliveryBatchId and ContractDeliveryItemId in OrderItemViewDto & OrderViewDetailsDto for FE edit display

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonDetailController.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Enable creating an **Order** together with its **OrderItems** in a single request from FE by mapping `CreatedBy` from JWT claims on the server and relaxing DTO validation that previously blocked the flow.
---
- **Auth & Ownership**
- Resolve `userId → managerId` (supports `BusinessManager` or `BusinessStaff → Supervisor`).
- Enforce seller ownership: `DeliveryBatch.Contract.SellerId` must match resolved manager.
- Prevent duplicate order for the same `DeliveryBatchId`.
- **DTO & Validation**
- `OrderCreateDto.CreatedBy` is ignored for input (server sets from claims).
- Keep business rules; allow optional `DeliveryRound`.
- Clearer date validations and item validations.
- **Mapping & Totals**
- Add `MapToNewOrder(orderCode, userId)` → sets `CreatedBy`, builds nested `OrderItems`, computes …
=> fix(order): allow creating Order with nested OrderItems by mapping CreatedBy from claims and relaxing validation

Database/DakLakCoffee_SCM.sql
Convert sample `Products` seed data from English to Vietnamese for better localization,  
and change approver role from **Admin** to **BusinessManager** to align with the business workflow.
---
- Translated `ProductName`, `Description`, `EvaluatedQuality`, and `ApprovalNote` fields from English to Vietnamese.
- Updated seed SQL to set `ApprovedBy` using `BusinessManager` account instead of `Admin`.
- Ensured region, location, and other product metadata are in Vietnamese for consistency.
- Verified that seed values match existing product enum/status definitions.
---
---
---
1. Open `Database/DakLakCoffee_SCM.sql` and run the updated seed script in the database.
2. Query `Products` table:
```sql
SELECT * FROM Products WHERE …
```
=> feat(seed): update Products seed data to Vietnamese, change approver role from Admin to BusinessManager

Database/DakLakCoffee_SCM.sql, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/ProcurementPlansDetail.cs
- Refactor the database schema and SQL scripts to allow the `ProcessMethodID` field in the Procurement Plan Detail table to accept `NULL` values.
- Update the DBContext or ORM mappings to reflect the nullable `ProcessMethodID` property, ensuring it aligns with the database schema.
- Modify related entity models and DTOs to accommodate the optional nature of `ProcessMethodID`.
- Adjust any business logic or validation rules that currently require `ProcessMethodID` to be non-null, making them conditional or optional as appropriate.
- Ensure that data insertion, update, and retrieval operations handle `NULL` values for `ProcessMethodID` correctly without causing errors.
- Test the changes thoroughly to confirm that allowing nulls does not break existing functionality or introduce …
=> refactor(sql, DBContext) Allow ProcessMethodID to be null in procurement plan detail

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
Fix and harden contract validations:
- Ensure `SignedAt` is **on or before** `StartDate` using **date-only** comparison (avoid false positives when times differ on the same day).
- Correct/align `TotalValue` calculation and validation with per-item sums and discount logic.
---
- Adjusted validation in `ContractCreateDto`/`ContractUpdateDto`:
- `SignedAt <= StartDate` using `DateOnly.FromDateTime(...)` (or equivalent) to compare by day.
- Consistent numeric guards for `TotalQuantity` / `TotalValue` (non-negative, coherent with items).
- Updated item DTO validations (`ContractItemCreateDto`/`ContractItemUpdateDto`) to keep sums coherent with contract header totals.
- Controller/Service logic updated to re-check and compute totals consistently.
- Minor refactors for clarity and error …
=> fix(contract): correct TotalValue logic; allow SignedAt on/before StartDate

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
Bring **Update** of `ContractDeliveryBatch` to full parity with **Create** business rules:
- Enforce delivery round limits and valid round index.
- Cap totals at contract level and batch level.
- Validate per-ContractItem cumulative quantities across all batches.
- Ensure every delivery item **belongs to the contract**.
- Exclude the **current batch** from cross-batch sums; ignore **soft-deleted** records.
---
- **Service (ContractDeliveryBatchService):**
- Exclude current batch when counting/summing existing batches.
- Validate `DeliveryRound ∈ [1, DeliveryRounds]` and total batch count ≤ `DeliveryRounds`.
- Ensure `Σ(planned of all batches) + current planned ≤ Contract.TotalQuantity`.
- Ensure `Σ(planned of items in this batch) ≤ Batch.TotalPlannedQuantity`.
- Ensure, for each …
=> fix(contract-delivery-batch): support updating batch with nested ContractDeliveryItems; align Create & Update business rules

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemViewDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Refactor the **OrderItem discount field** to be stored and processed as a **percentage** instead of an absolute amount.  
This ensures consistency in order calculations, improves flexibility, and aligns with the business flow for applying discounts in percentages.
---
- Updated **OrderItemCreateDto**, **OrderItemUpdateDto**, and **OrderItemViewDto** to use `DiscountPercent` instead of discount amount.  
- Adjusted **OrderMapper** to correctly map discount percentage between DTOs and entities.  
- Modified **OrderService** to handle discount as percentage in calculations.  
- Ensured order total calculation reflects percentage-based discount logic.
---
- `OrderItemCreateDto.cs`  
- `OrderItemUpdateDto.cs`  
- `OrderItemViewDto.cs`  
- `OrderMapper.cs`  
- `OrderService.cs`  
---
- N/A (all …
=> feat(order-item): change discount field to percentage instead of absolute amount (update DTOs, mapper, service)

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationCreateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationUpdateDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationViewAllDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationViewDetailsDto.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/PaymentConfigurationEnums/FeeType.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/PaymentConfigurationMapper.cs, Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentConfigurationService.cs
Refactor the PaymentConfiguration module to use **enum FeeType** instead of raw strings.  
This improves type-safety, prevents invalid values, and makes the API contracts clearer for both backend and frontend.  
---
- Replaced `string FeeType` with `enum FeeType` in all PaymentConfiguration DTOs.  
- Added `PaymentConfigurationEnums/FeeType.cs` with defined values (Registration, MonthlyMaintenance, QuarterlyMaintenance, YearlyMaintenance, PurchasePlanPosting, Other).  
- Updated `PaymentConfigurationMapper` to handle enum ↔ string conversion when mapping between Entity and DTO.  
- Refactored `PaymentConfigurationService` logic to align with enum usage.  
- Applied `[JsonConverter(typeof(JsonStringEnumConverter))]` for proper JSON serialization/deserialization of enum values.  
---
- …
=> feat(payment-config): switch FeeType to enum (DTOs, Mapper, Service) and add PaymentConfigurationEnums
