PhucLHSE/DakLakCoffeeSupplyChain_BE

Database/DakLakCoffee_SCM.sql
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UserAccountsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/UserAccountDTOs/UserAccountCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DakLakCoffeeSupplyChain.Common.csproj
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/UserAccountEnums/LoginType.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/Security/IPasswordHasher.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/Security/PasswordHasher.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/GenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/IGenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IRoleRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IUserAccountRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/RoleRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/UserAccountRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/UserCodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IUserAccountService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs

This pull request implements the **Create UserAccount API** including full validation, entity mapping, and RESTful response handling. It is part of the core user management system in the DakLak Coffee Supply Chain backend.
---
- Valid email format + uniqueness
- Phone number (optional) + uniqueness
- Password complexity (uppercase, lowercase, digit, special character, min length 10)
- Role existence (by role name)
- `201 Created`: on success
- `409 Conflict`: duplicate email/phone
- `400 BadRequest`: invalid input model
- `500 InternalServerError`: unexpected error
---
- `UserAccountCreateDto.cs`
- `Enum/UserAccountEnums/LoginType.cs`
- `Helpers/Security/IPasswordHasher.cs`, `PasswordHasher.cs`
- `Generators/ICodeGenerator.cs`, `UserCodeGenerator.cs`
- `IRepositories/IRoleRepository.cs`, …

feat(user): implement Create UserAccount API with full validation and response mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/ProductEnums/ProductStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProductRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProductRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

This commit delivers the complete backend implementation for retrieving a list of products within the supply chain platform.  
The API supports business-side and admin-side functionalities such as browsing product stock, filtering product info, and preparing for order/contract creation.
---
- **`ProductController`**: added `GetAll()` HTTP GET endpoint for client access.
- **`ProductService`**: retrieves product data with related entities (`CoffeeType`, `Inventory`, `ProcessingBatch`).
- **`ProductMapper`**: safely converts entities to lightweight `ProductViewAllDto` objects.
- **`ProductViewAllDto`**: designed for fast UI rendering, includes essential fields only.
- **`ProductStatus` enum**: centralized all valid status values (e.g., `Draft`, `Approved`, `InStock`, etc.).
- …

feat(product): add GetAll Product API with controller, service, mapper, and DTO integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProductRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProductRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

This pull request implements the full backend support for retrieving detailed product information by its unique identifier (`ProductId`). This API is essential for displaying individual product records in detail views such as admin panels, business inventory, or product review modules.
---
- **`ProductsController.GetById(Guid id)`**: added GET endpoint `/api/products/{id}`.
- **`IProductService.GetByIdAsync()` & `ProductService`**: contains logic to include navigation properties.
- **`IProductRepository` & `ProductRepository`**: fetches product entity with related data (CoffeeType, Inventory → Warehouse, Batch, ApprovedBy).
- **`ProductViewDetailsDto`**: newly added DTO class that exposes detailed product fields such as:
- Full description
- Origin location & certification
- Evaluation …

feat(product): implement GetById Product API with full details, mapper, and DTO integration

---

README.md

This commit refines the **Actors** and **Business Flows Implemented** sections in the `README.md` file.
- Updated actor descriptions to better reflect each role's actual responsibilities in the platform (e.g., Business Staff, Delivery Staff).
- Revised business flow explanations to align with newly implemented backend features, including:
- Cultivation registration and farming commitments tracking
- Post-harvest batch logging and expert evaluations
- Contract-based order processing and delivery status updates
These adjustments ensure that the README accurately represents the current backend logic and helps new contributors or reviewers understand the system context more clearly.

docs(readme): refine Actors and Business Flows sections for updated role descriptions

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/RolesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/RoleDTOs/RoleViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/RoleEnums/RoleStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IRoleRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ISystemConfigurationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IRoleService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/RoleService.cs

This PR adds the `GET /roles` endpoint to retrieve all roles in the system.  
The response returns simplified role data using `RoleViewAllDto`.
---
- Added `RoleViewAllDto` to represent role data (RoleId, RoleName, Status).
- Implemented `MapToRoleViewAllDto()` mapper for Role entity.
- Created service method `GetAll()` in `IRoleService` and `RoleService`.
- Created controller endpoint `GetAll()` in `RolesController`.
---
To support the management interface where Admins can:
- View a list of system roles
- Use this data to assign roles to user accounts
---
- Endpoint: `GET /api/roles`
- Response: List of roles with `RoleId`, `RoleName`, `Status`
- Status: ✅ Tested locally with Swagger
---

feat(role): implement GetAll Role API with DTO mapping and service integration

---

Database/DakLakCoffee_SCM.sql

This PR adds complete data for:
- Full crop progress timeline (`CropProgresses`) from flowering to harvesting
- Seeded all 5 standard processing methods:
- Natural
- Washed
- Honey
- Semi-washed
- Carbonic maceration
- Each method includes its own ordered stage sequence (`ProcessingStages`)
---
- Support frontend team to test full timeline rendering in Luồng 2
- Enable Business Staff to configure accurate post-harvest workflows in Luồng 3
- Prepare stage-based tracking logic for future expert evaluation
---
- `CropProgresses`
- `ProcessingMethods`
- `ProcessingStages`
---
- All foreign keys resolved
- OrderIndex and StepIndex provided for timeline-based logic
- Can be used immediately for dropdowns, UI timeline, and mock tracing

feat(seed): add full crop progress timeline and all processing methods with standardized stages

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/RolesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/RoleDTOs/RoleViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IRoleService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/RoleService.cs

This pull request introduces the **GetById API for Role**, allowing clients to retrieve detailed information of a specific Role by its unique identifier.
---
- ✅ Added `RoleViewDetailsDto` in `Common.DTOs.RoleDTOs`
- ✅ Implemented `GetByIdAsync(int id)` in `IRoleService` and `RoleService`
- ✅ Mapped `Role` entity to `RoleViewDetailsDto`
- ✅ Added endpoint in `RoleController`:

feat(role): implement GetById API with RoleViewDetailsDto and service mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/GenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/IGenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs

This pull request refactors the `ProductService` and `UserAccountService` to use the newly implemented **generic methods** from `GenericRepository<T>`:
- ✅ `GetAllAsync(...)` with support for:
- `Include(...)` and `ThenInclude(...)`
- `OrderBy(...)`
- `AsNoTracking`
- ✅ `GetByIdAsync(...)` using dynamic predicate and flexible includes
---
- Improves **code reusability** across multiple services
- Reduces **boilerplate logic** in repositories
- Ensures consistency in handling entity retrieval logic
---
| Layer       | Changes made                    |
|-------------|----------------------------------|
| Repository  | Added `GetAllAsync` & `GetByIdAsync` in `GenericRepository` |
| Services    | Refactored `ProductService` and `UserAccountService` to use the generic methods |
| DTO Mapping | …

refactor(service): apply generic GetAllAsync and GetByIdAsync in Product and UserAccount services

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcurementPlansController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/ProcurementPlanEnums/ProcurementPlanStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcurementPlanRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcurementPlanRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcurementPlanService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

This pull request implements the following features for the `Procurement Plan` module:
- Supports retrieving detailed information of a procurement plan by its ID.
- Includes full mapping of related data through DTO and mapper integration.
- Supports retrieving the list of procurement plans with full details.
- Integrated DTO and mapper to provide a consistent and structured output.
- Merged the latest `main` branch to ensure the feature branch is up-to-date.
- No modifications were made to the merged `product` feature (coming from another PR).
1. Use API client (Postman, Swagger, etc.).
2. Test the following endpoints:
- `GET /api/procurementPlan/{id}` → returns details of a specific Procurement Plan.
- `GET /api/procurementPlan` → returns list of all Procurement Plans.
3. Verify response …

Implement Procurement Plan GetById & GetAll API with full details and DTO mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/Flow3DTOs/ProcessingMethod/ProcessingMethodViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingMethodRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingMethodRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingMethodMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs

This pull request implements the **GetAll Processing Method API**, with full integration from repository to controller.
---
- Created DTOs:
- `ProcessingMethodViewAllDto`
- `ProcessingMethodDetailDto`
- Implemented mapper:
- `ProcessingMethodMapper.cs`
- Added service logic:
- `IProcessingMethodService.GetAll()`
- `ProcessingMethodService.GetAll()`
- Integrated API controller:
- `ProcessingMethodController.cs`
- Standardized response using `ServiceResult`
- Added basic null/empty data handling
---

feat(processingMethod): implement GetAll Processing Method API with DTO mapping and service integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/Flow3DTOs/ProcessingMethod/ProcessingMethodDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingMethodMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs

This pull request adds the API endpoint to retrieve a **single Processing Method** by its ID, including detailed data and related processing stages count.
---
- Added service method:
- `IProcessingMethodService.GetById(int methodId)`
- `ProcessingMethodService.GetById(...)`
- Implemented detailed DTO:
- `ProcessingMethodDetailDto` (includes stage count)
- Used `ProcessingMethodMapper.MapToProcessingMethodDetailDto`
- Integrated new API endpoint:
- `GET /api/ProcessingMethod/{methodId}`
- Response includes:
- Method ID, Code, Name, Description
- Number of related processing stages
---

feat(processingMethod): implement GetById Processing Method API with DTO mapping and service integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/Flow3DTOs/ProcessingMethod/ProcessingMethodDeleteDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs

🗑️ Feature: DeleteById Processing Method API
This pull request adds the API endpoint to delete a Processing Method by its unique ID. If the method exists and is not in use, it will be removed from the system.
✅ Changes Made
Added service method:
IProcessingMethodService.DeleteById(int methodId)
ProcessingMethodService.DeleteById(...)
Integrated delete logic in:
ProcessingMethodController.DeleteById(...)
Added status handling and validation:
Checks if method exists before deletion
Prevents deletion if the method is associated with any stages (optional logic)
Integrated new API endpoint:
DELETE /api/ProcessingMethod/{methodId}
Response includes:
Success message or error (e.g., NotFound, Conflict)
---

feat(processingMethod): implement DeleteById Processing Method API with DTO mapping and service integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcurementPlansController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessManagerDTOs/ProcurementPlanViews/BusinessManagerSummaryDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcurementPlanDetailsRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcurementPlanRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcurementPlanDetailsRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcurementPlanRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcurementPlanService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

This PR refactors the **Get All Procurement Plan API** to provide:
- Full procurement plan details
- Integration with `AutoMapper` for DTO transformation
- Clean separation between Entity and DTO layers
- Refactored `ProcurementPlanService.GetAllAsync` to return DTOs instead of entities
- Added new `ProcurementPlanDto` and mapping profile
- Ensured `Include` for related entities to avoid lazy loading issues
- Updated `ProcurementPlansController` endpoint to use the new service method
- Improve API response consistency and avoid leaking internal entities
- Prepare the API for front-end consumption with clean DTOs
- Enable easier future maintenance and testing of service logic
- ✅ Manual testing via Swagger — verified correct data returned
- ✅ Checked edge cases with empty result sets
- ✅ …

refactor(procurementPlan): refactor Get All Procurement Plan API with full details, mapper, and DTO integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseInboundRequestsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseInboundRequestDTOs/WarehouseInboundRequestViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/WarehouseInboundRequestEnums/InboundRequestStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IBusinessStaffRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/BusinessStaffRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/INotificationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseInboundRequestService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseInboundRequestMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/NotificationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseInboundRequestService.cs

✅ Validate request existence and current status
✅ Retrieve BusinessStaff by logged-in user ID
✅ Update request status using InboundRequestStatus enum (Pending → Approved)
✅ Assign BusinessStaffId, update timestamps
✅ Send internal notification and email to the corresponding farmer

feat(flow4): approve inbound request using enum status

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseInboundRequestsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseInboundRequestDTOs/WarehouseInboundRequestDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IWarehouseInboundRequestRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseInboundRequestRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseInboundRequestService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseInboundRequestMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseInboundRequestService.cs

Add API to view warehouse material request details.
Create WarehouseInboundRequestDetailDto
Map toDetailDto()
Add endpoint GET /api/WarehouseInboundRequests/{id}
Include Farmer, Staff, Batch, CoffeeType, CropSeason information.
Serve Flow 4 - Warehouse Management.

feat(inbound-request): implement view detail API and DTO mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehousesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseDTOs/WarehouseCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IWarehouseRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseService.cs

- Add warehouse creation logic
- Include name duplication check
- Use `WarehouseCreateDto` for input validation

feat(warehouse): create new warehouse with validation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessManagerDTOs/BusinessManagerViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBussinessManagerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessManagerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs

This pull request implements the `GetById` API for the **BusinessManager** module using the `BusinessManagerViewDetailsDto`.
---
- Added `BusinessManagerViewDetailsDto` for detailed response structure.
- Implemented `GetByIdAsync` method in:
- **Repository layer**: fetches data with `Include(User)`
- **Service layer**: maps entity to DTO
- **Controller layer**: exposes GET endpoint
- Added null-checks and safe string defaults in mapper.
---
Follows **3-layer architecture**:
- **Controller** → `BusinessManagerController.GetById`
- **Service** → `BusinessManagerService.GetByIdAsync`
- **Repository** → `BusinessManagerRepository.GetByIdAsync`
---
- Navigation property `User` is eagerly loaded via `.Include(x => x.User)`
- DTO includes `FullName`, `Email`, and `PhoneNumber` from linked `User` …

feat(business-manager): implement GetById API with ViewDetailsDto and 3-layer structure

---

Database/DakLakCoffee_SCM.sql

This PR seeds initial data for the core payment flow, enabling backend logic and integration tests for payment-related modules.
---
- **PaymentConfigurations**  
- Added fee settings for:
- `BusinessManager`: Registration (1,000,000đ) & MonthlyFee (400,000đ)
- `Farmer`: Registration (200,000đ) & AnnualMaintenanceFee (300,000đ, effective from 2025-07-01)
- **Payments**  
- Sample transactions paid via **VNPay**:
- BusinessManager registration & monthly fee
- Farmer registration
- **Wallets**  
- Created:
- System wallet with total balance: 1,600,000đ
- User wallets (BusinessManager, Farmer) with balance: 0đ
- **WalletTransactions**  
- Logged top-up transactions into the system wallet, based on the above payments.
---
- All payments use **VNPay** as `PaymentMethod`.
- Descriptions in …

feat(payment): seed initial data for PaymentConfigurations, Payments, Wallets, and WalletTransactions with VNPay logic

---

Database/DakLakCoffee_SCM.sql
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessBuyerDTOs/BusinessBuyerCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/ClaimsHelper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IBusinessBuyerRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IBusinessManagerRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/BusinessBuyerRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/BusinessManagerRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessBuyerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs

This PR implements the `Create` API for BusinessBuyer with complete integration across controller, service, repository, DTO, and helper layers.
---
- Add `BusinessBuyerCreateDto` with full validation rules.
- Implement `BusinessBuyersController.CreateBusinessBuyerAsync` with token-based user identification.
- Add role verification to ensure only `BusinessManager` can create buyers.
- Generate unique `BuyerCode` based on ManagerCode and current year.
- Prevent duplication based on `TaxId` + `CreatedBy`.
- Add `ClaimsHelper` for extracting user ID, role, email from JWT.
- Use `MapToNewBusinessBuyer()` for clean mapping from DTO to Entity.
- Update SQL schema: extend `BuyerCode` column to `VARCHAR(50)`.
---
- …

feat(business-buyer): implement create API with validation, code gen, role check, and full service/controller integration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessManagerDTOs/BusinessManagerCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessManagerDTOs/BusinessManagerUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/RoleDTOs/RoleCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/RoleDTOs/RoleUpdateDto.cs

This pull request refactors and enhances the `BusinessBuyersController` and related DTOs by:
- Updating the `GetAll` logic for BusinessBuyer to use consistent user ID parsing via `ClaimsHelper`.
- Ensuring validation messages in all DTOs (BusinessManagerCreateDto, BusinessManagerUpdateDto, RoleCreateDto, RoleUpdateDto) are localized in **Vietnamese** for a better user experience.
---
- `BusinessBuyersController.cs`: improved GetAll by unifying the userId extraction logic.
- `BusinessManagerCreateDto.cs`, `BusinessManagerUpdateDto.cs`: translated validation messages to Vietnamese.
- `RoleCreateDto.cs`, `RoleUpdateDto.cs`: translated validation messages to Vietnamese.
---
- Send a `GET /api/businessbuyers` request while authenticated as a `BusinessManager`.
- Try submitting invalid data to …

refactor(dto, controller): update BusinessBuyer GetAll logic and localize validation messages to Vietnamese

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CoffeeTypeController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CoffeeTypeDTOs/CoffeeTypeViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICoffeeTypeRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CoffeeTypeRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICoffeeTypeService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CoffeeTypeMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CoffeeTypeService.cs

This pull request implements the API that allows clients to retrieve a list of all available coffee types.
- Endpoint: `GET /api/CoffeeType`
- Returns list of coffee types with relevant metadata (e.g., name, origin, description, status)
- Includes pagination and optional filtering (e.g., by status or region) [if applicable]
- Provides foundational API for both internal dashboards and frontend clients to access master coffee data
- Standardized response schema with status codes and message field
- Designed for easy extension (e.g., adding image, flavor profile in future)
- Unit tests for service and repository layers
- Integration test for endpoint response (success & error cases)
---
Further enhancements could include support for localization or grouping by coffee families (Arabica, …

feat(CofeeType) Implement View all coffee types API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CoffeeTypeController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICoffeeTypeService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CoffeeTypeService.cs

This pull request adds the API to retrieve detailed information about a specific coffee type by its unique identifier.
- Endpoint: `GET /api/CoffeeType/{typeId}`
- Fetches detailed information about a coffee type:
- `id`
- `name`
- `origin`
- `description`
- Returns 404 if coffee type does not exist
- Clear and consistent response schema
- Ensures proper error handling and input validation
- Unit tests for the service logic
- Integration tests for endpoint:
- Successful retrieval
- Not found case
- Invalid ID format
---
Future work could include audit logging and support for soft-deleted coffee types.

feat(CofeeType) Implement View by id coffee type API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessBuyerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs

This PR introduces a new **hard delete API** for `BusinessBuyer`, along with formatting improvements in the `UnitOfWork` class for better readability and consistency.
---
- Added new service method: `DeleteById` (hard delete) in `BusinessBuyerService`
- Added corresponding endpoint in `BusinessBuyersController`
- Updated `IBusinessBuyerService` with the new method
- Reformatted `UnitOfWork.cs`:
- Standardized spacing and method order
- Removed redundant comments or lines (if any)
---
- `IBusinessBuyerService.cs`
- `UnitOfWork.cs`
---
- ✅ Verified deletion works as expected (record removed from database)
- ✅ Confirmed behavior when deleting non-existent or already-deleted entries
- ✅ No breaking changes to other APIs
---
- This …

feat(business-buyer): implement hard delete API and refactor UnitOfWork formatting

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropProgressesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropProgressDTOs/CropProgressCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICropProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICultivationRegistrationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CultivationRegistrationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropProgressService.cs

This pull request implements the full `Create` functionality for `CropProgress` entity, following the established service-repository pattern.
- `CropProgressCreateDto` + `CropProgressViewDetailsDto`
- Mapper: `MapToCropProgressCreateDto()` and `ToViewDetailsDto()`
- Validation logic for:
- `StageId` existence
- `CropSeasonDetailId` validity
- `UpdatedBy` (FarmerId) existence
- No duplicate: `(StageId + ProgressDate + CropSeasonDetailId)`
- Repository method: `GetCropSeasonDetailByIdAsync`
- Controller: `POST /api/CropProgress`
- Service returns clean `ServiceResult`
- All foreign key references are checked before saving
- Date cannot be in the future
- Farmer must exist in `Farmers` table (checked via `UpdatedBy`)
(Attach Postman or Swagger test screenshot here)
---
Closes …

feat: implement CropProgress creation with full business validation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CoffeeTypeController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CoffeeTypeDTOs/CoffeeTypeCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICoffeeTypeRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CoffeeTypeRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICoffeeTypeService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CoffeeTypeMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CoffeeTypeService.cs

This pull request introduces an API endpoint to create new coffee types in the system.
- Endpoint: `POST /api/coffee-types`
- Accepts input fields:
- `name`
- `origin`
- `description`
- `status` (e.g. active/inactive)
- Validates input fields with proper constraints (e.g., required `name`, max length on `description`)
- Returns:
- `201 Created` with new coffee type data
- `400 Bad Request` for invalid input
- Handles duplicate name cases gracefully
- Unit tests for validation logic and service methods
- Integration tests for:
- Successful creation
- Missing or invalid fields
- Duplicate entries
---
This API lays the foundation for managing coffee type catalogs and will support additional features such as updates, deactivation, and linking with procurement plans.

feat(CofeeType) Implement Create coffee type API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CoffeeTypeController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CoffeeTypeDTOs/CoffeeTypeUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICoffeeTypeService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CoffeeTypeMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CoffeeTypeService.cs

This pull request introduces the API endpoint to update an existing coffee type by its ID.
- Endpoint: `PUT /api/coffee-types/{id}`
- Accepts update payload with any of the following fields:
- `name`
- `origin`
- `description`
- `status`
- Performs partial or full update of the coffee type
- Includes input validation and proper error handling
- Handles edge cases:
- Coffee type not found → `404 Not Found`
- Invalid data → `400 Bad Request`
- Duplicate name conflict → `409 Conflict`
- Unit tests for update logic and validation
- Integration tests for:
- Successful update
- Non-existent ID
- Invalid input payload
---
This API completes the core CRUD functionality for coffee type management and sets the stage for future enhancements such as audit tracking or approval flows.

feat(CofeeType) Implement Update coffee type API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingStageController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodStageDTOs/ProcessingStageUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingStageRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingStageRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingStageService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingStageMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingStageService.cs

- Added `UpdateAsync` method in `ProcessingStageService`
- Integrated `ProcessingStageUpdateDto` to map update request
- Implemented `MapToProcessingStageUpdateEntity` in `ProcessingStageMapper`
- Ensured entity existence check before update
- Returned appropriate `ServiceResult` codes and messages
- Validates and updates `StageCode`, `StageName`, `Description`, `OrderIndex`, `IsRequired`, and `MethodId`
- If stage does not exist, returns warning with meaningful message
- Proper enum/constants (`Const`) used for status codes/messages
- `ProcessingStageService.cs`
- `IProcessingStageService.cs`
- `ProcessingStageMapper.cs`
- `ProcessingStageUpdateDto.cs`

feat: implement update functionality for ProcessingStage

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemDeleteDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs

This pull request introduces the **soft delete functionality for individual contract items**, ensuring that items can be logically removed from the system without actual deletion from the database.
- ✅ Implemented `IContractItemService` and `ContractItemService` with `SoftDeleteContractItemById` logic.
- ✅ Created new API endpoint: `PATCH /api/contract-items/soft-delete/{contractItemId}`.
- ✅ Ensured `IsDeleted` flag and `UpdatedAt` are updated properly.
- ✅ Added `ContractItemsController` for modular management of contract items.
- ✅ Prevented re-deletion of already deleted items (`IsDeleted == true` check).
- ✅ Applied `VietnamTime` via `DateHelper.NowVietnamTime()`.
1. Make a `PATCH` request to:
/api/contract-items/soft-delete/{contractItemId}
2. Ensure that:
- `IsDeleted = true` for …

feat(contract-item): implement soft delete API with service, controller, and DTO integration

---

.github/PULL_REQUEST_TEMPLATE.md

Establish a standardized pull request template to ensure team-wide consistency in documenting changes, test instructions, and related links.
---
- Created `PULL_REQUEST_TEMPLATE.md` file under `.github/` directory
- Wrote a structured markdown format including: Feature, Objective, Key Changes, How to Test, Test Cases, Notes, Related
- Added placeholders to guide contributors on how to write high-quality PR descriptions
- Applied GitHub-compatible formatting (headings, lists, checkboxes, JSON blocks)
---
- `.github/PULL_REQUEST_TEMPLATE.md`
---
- `PULL_REQUEST_TEMPLATE.md`
---
1. Merge the template file into the `main` branch
2. Create a new pull request from any branch → `main`
3. Confirm that the description box auto-populates with the defined template content
---
---
- This template …

chore(template): add default pull request template

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs

Implement the ability for `BusinessManager` users to update an existing `ContractItem`, including fields like `CoffeeType`, `Quantity`, `UnitPrice`, and `Note`. The update process includes validation, duplicate checks, and consistent response formatting.
---
- Added `Update` method to `ContractItemService` with full business logic and validation
- Mapped `ContractItemUpdateDto` to `ContractItem` entity using a dedicated mapper
- Added duplicate check for `CoffeeTypeId` within the same contract (excluding self)
- Implemented `PUT /api/contractitems/{id}` endpoint in controller with role restriction
- Integrated `ModelState` validation, `IValidatableObject` rules, and structured `IServiceResult` responses
---
- …

feat(contract-item): implement update API with validation, duplicate check, and response mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingParameterDTOs/ProcessingParameterViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingParameterRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingParameterRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingParameterService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingParameterMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingParameterService.cs

Triển khai tính năng **xem danh sách các thông số chế biến** (`ProcessingParameter`) cho hệ thống quản lý chuỗi cung ứng cà phê.  
Phục vụ vai trò quản lý và giám sát tiến trình các bước chế biến, đảm bảo đúng thông số kỹ thuật được ghi nhận.
---
- Thêm `ProcessingParameterViewAllDto` để chuẩn hóa dữ liệu trả ra
- Viết hàm mapping từ entity → DTO trong `ProcessingParameterMapper`
- Tạo `IProcessingParameterService` và implement logic `GetAll()` trong service
- Viết hàm `GetAllActiveAsync()` tại repository để lọc `IsDeleted = false`
- Tạo controller `ProcessingParameterController` và route `GET /api/processingparameter/get-all`
- Trả về `ServiceResult` chuẩn gồm `SUCCESS` hoặc `NO_DATA` code
---
- `ProcessingParameterViewAllDto.cs`
- `ProcessingParameterMapper.cs`
- …

feat(processing-parameter): implement ViewAll (GetAll) API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingParameterDTOs/ProcessingParameterViewDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingParameterRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingParameterRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingParameterService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingParameterMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingParameterService.cs

Cung cấp API để truy xuất thông tin chi tiết của một `ProcessingParameter` theo `ParameterId`.  
Phục vụ việc giám sát các thông số kỹ thuật của từng bước trong quá trình chế biến cà phê.
---
- Thêm `ProcessingParameterViewDetailDto` chứa đầy đủ thông tin chi tiết
- Viết mapper `MapToProcessingParameterDetailDto()` để chuyển từ entity sang DTO
- Bổ sung `GetByIdAsync(Guid id)` trong `IProcessingParameterRepository` và implement với `IsDeleted == false`
- Thêm method `GetById()` vào `IProcessingParameterService` và `ProcessingParameterService`
- Thêm endpoint: `GET /api/processingparameter/{parameterId}` trong controller
- Xử lý HTTP code:
- `200`: thành công
- `404`: không tìm thấy hoặc đã bị xóa mềm
- `500`: lỗi hệ thống
---
- `ProcessingParameterViewDetailDto.cs`
- …

feat(processing-parameter): implement GetById (ViewDetail) API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseReceiptsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseReceiptDTOs/WarehouseReceiptDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseReceiptDTOs/WarehouseReceiptListItemDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IWarehouseReceiptRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseInboundRequestRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseReceiptRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseReceiptService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseOutboundRequestService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseReceiptService.cs

feat: add GetAllAsync and GetByIdAsync for WarehouseReceipt; expose new endpoints in controller
Enable users (Admin/BusinessStaff/Manager) to view all warehouse receipts and get receipt details via API.
---
- Implement `GetAllAsync` to list all warehouse receipts (filtered by `IsDeleted`)
- Implement `GetByIdAsync` to fetch receipt details with full relational data
- Add corresponding controller endpoints:
- `GET /api/warehousereceipts`
- `GET /api/warehousereceipts/{id}`
- Authorize access to roles: Admin, BusinessStaff, Manager
---
- `WarehouseReceiptService.cs`
- `IWarehouseReceiptService.cs`
- `WarehouseReceiptsController.cs`
- `[WarehouseReceiptDetailDto.cs, WarehouseReceiptListItemDto.cs]` (if added/updated)
---
- Controller methods: `GetAll()`, `GetById(Guid id)`
---
1. Use Swagger …

feat: add GetAllAsync and GetByIdAsync for WarehouseReceipt

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingParameterDTOs/ProcessingParameterUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingParameterService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingParameterService.cs

Thêm API `PUT /api/processingparameter` để **chỉnh sửa thông số** trong quá trình chế biến (ProcessingParameter). Hỗ trợ sửa giá trị, đơn vị đo, thời gian ghi nhận...
---
- Thêm `UpdateAsync()` trong `IProcessingParameterService` và `ProcessingParameterService`
- Viết logic cập nhật entity + check tồn tại + validate
- Map từ `ProcessingParameterUpdateDto` → Entity
- Trả về DTO chi tiết sau khi cập nhật
---
- `ProcessingParameterController.cs`
- `ProcessingParameterService.cs`
- `IProcessingParameterService.cs`
- `ProcessingParameterUpdateDto.cs`
- `ProcessingParameterMapper.cs`
---
- PUT API: `/api/processingparameter`
- UpdateDto: `ProcessingParameterUpdateDto.cs`
---
1. Gửi request PUT:
```json
{
"parameterId": "guid-cần-update",
"progressId": "guid-progress",
"parameterName": …
```

[ProcessingParameter] Add Update functionality (PUT API)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IContractRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ContractRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs

Implement a new API that allows `BusinessManager` to create a contract with nested `ContractItems`. Includes validation, duplication check, code generation, and role-based access control.
---
- Added `POST /api/contracts` endpoint
- Service logic:
- Role validation for `BusinessManager`
- Check duplicate `ContractNumber` (per Seller)
- Sum and compare `TotalQuantity`, `TotalValue` with line items
- Generate `ContractCode` and `ContractItemCode`
- DTO-level validation via attributes and `IValidatableObject`
- Auto-mapping nested contract items from DTO → Entity
---
- `IContractService.cs`
- `ContractRepository.cs`
- `IContractRepository.cs`
- `CodeGenerator.cs`
- `ICodeGenerator.cs`
---
- `ContractCreateDto.cs`
---
1. …

feat(contract): add Create Contract API with DTO validation, duplicate check, code generation, and nested item mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/AuthController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AuthDTOs/ForgotPasswordRequestDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AuthDTOs/ResetPasswordRequestDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IAuthService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/AuthService.cs

Feature: Reset Password API
📌 Objective
Purpose of this PR: Implement the reset password functionality. This API will send an OTP via email to the user and allow them to set a new password if the OTP is valid.
✅ Key Changes
Added Reset Password API:
Added the POST /api/Auth/reset-password endpoint to change the user's password.
Added GET /api/Auth/reset-password/userId={userId}&token={token} to verify the OTP and validate the request.
Temporarily store OTP in memory (cache).
Send an email with a link to reset the password containing the OTP.
Handling OTP Verification:
Verify the OTP and userId to confirm the validity of the reset password request.
Update the password if the OTP is valid and remove it from the cache.
Error Handling:
If the OTP is invalid or expired, return an error …

feat(auths): Implement forgot and reset password

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

Refactor `GetAllProductsAsync` logic to support both **BusinessManager** and **BusinessStaff** in viewing products. This change ensures that staff can see products created by their supervising manager, not just managers themselves.
---
- Refactored `ProductService.GetAll(Guid userId)` to resolve `ManagerId` from both Manager and Staff accounts.
- Updated `ProductsController` to extract `userId` from JWT token and pass it into the service.
- Applied role-based access logic via `CreatedBy == ManagerId`, enabling shared access between manager and staff.
---
- `ProductsController.cs`
- `IProductService.cs`
---
- _(No new files added)_
---
1. **Login** as either:
- `BusinessManager` (token contains userId = ManagerId)
- `BusinessStaff` (token contains userId = StaffId → …

refactor(product): unify GetAll logic for Manager and Staff by resolving ManagerId from UserId

---

Database/DakLakCoffee_SCM.sql

This PR adds initial seed data for batch evaluations and progressive waste tracking within a natural coffee processing workflow. It supports full traceability and sustainability analysis, primarily related to the `Farmer` and `Expert` roles.
---
- Insert seed record for `ProcessingBatchEvaluations` with sample evaluation result.
- Add waste entries (`ProcessingBatchWastes`) for each processing step in `BATCH-2025-0001`.
- Insert corresponding disposal records (`ProcessingWasteDisposals`) using various methods (compost, bury, sell, reuse).
- Ensure waste tracking aligns with all four stages: Harvest, Drying, Hulling, and Grading.
---
- `DakLakCoffee_SCM.sql`
---
- N/A (data-only update)
---
1. Connect to the database and run `DakLakCoffee_SCM.sql` with the new insert statements.
2. Verify …

feat(seed): insert evaluation and multi-stage waste/disposal data for natural processing batch

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Triển khai API `GET /api/processing-batch` để truy xuất danh sách tất cả các mẻ chế biến (batch), dùng cho vai trò `BusinessManager` theo dõi chuỗi cung ứng.
---
- Thêm `GetAll()` trong `ProcessingBatchRepository` với `.Include(Farmer.User)` và `.Include(Method)`
- Cập nhật `IProcessingBatchRepository`, `IProcessingBatchService` và implementation
- Tạo DTO `ProcessingBatchViewDto` để trả dữ liệu rõ ràng cho FE
- Viết mapper `MapToViewDto()` trong `ProcessingBatchMapper.cs`
- Tạo route `GET /api/processing-batch` trong controller
---
- `ProcessingBatchRepository.cs`
- `IProcessingBatchRepository.cs`
- `IProcessingBatchService.cs`
- `ProcessingBatchController.cs`
- `ProcessingBatchMapper.cs`
- `ProcessingBatchViewDto.cs`
---
- `ProcessingBatchViewDto.cs` (DTO …

feat(ProcessingBatch): implement ViewALl APIs

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchsProgressViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

Cung cấp API để lấy danh sách toàn bộ tiến độ chế biến (`ProcessingBatchProgress`) theo từng lô sản xuất nhằm hỗ trợ hiển thị UI quản lý của vai trò quản lý chế biến (`BusinessManager`).
---
- Thêm interface `IProcessingBatchProgressService.GetAllAsync()`
- Cài đặt `ProcessingBatchProgressService` với logic gọi từ repository và map sang DTO
- Tạo DTO `ProcessingBatchProgressViewAllDto`
- Tạo `Mapper` tương ứng: `ProcessingProgressMapper`
- Tạo `Controller`: `ProcessingBatchProgressController.GetAll`
---
- `ProcessingBatchProgressViewAllDto.cs`
- `ProcessingProgressMapper.cs`
---
- Endpoint mới: `GET /api/ProcessingBatchProgress`
---
1. **Login** bằng tài khoản có role …

feat(ProcessingBatchProgress): Implement GetAll API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

Implement the `GET /api/ProcessingBatchsProgress/detail/{id}` endpoint to retrieve detailed information for a specific processing batch progress record by `progressId`.
---
- Added DTO: `ProcessingBatchProgressDetailDto`
- Implemented mapping in `ProcessingBatchProgressMapper`
- Repository method includes all necessary navigation properties
- Filters out deleted `ProcessingParameters` (`IsDeleted == false`)
- Extracts `UpdatedByName` from `Farmer.User.Name` relationship
---
- `ProcessingBatchProgressDetailDto.cs`
- `ProcessingBatchProgressMapper.cs`
---
1. Log in using an account with the `BusinessManager` role
2. Send a request to:
GET …

feat(ProcessingBatchProgress): Implement ViewById API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryBatchViewDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryItem/ContractDeliveryItemViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs

Implement a detailed API to retrieve a specific `ContractDeliveryBatch` by its ID. This includes nested delivery items, related contract information, and coffee type mapping. Applies to `BusinessManager` and `BusinessStaff` roles.
---
- Added `GetById` method in `ContractDeliveryBatchService` with full includes
- Mapped entity to new `ContractDeliveryBatchViewDetailDto` and nested `ContractDeliveryItemViewDto`
- Implemented new controller endpoint with role-based authorization
- Sorted delivery items by code and ensured null-safe access
- Handled missing data with default DTO and 404 response
---
- `ContractDeliveryBatchService.cs`
- `IContractDeliveryBatchService.cs`
- `ContractDeliveryBatchMapper.cs`
- `ContractDeliveryBatchsController.cs`
---
- `ContractDeliveryBatchViewDetailDto.cs`
- …

feat(contract-delivery-batch): implement GetById API with detail DTO, contract info, delivery items and coffee type mapping

---

Database/DakLakCoffee_SCM.sql

This pull request refactors the database-related logic and SQL mappings for the following entities:
- `ProcurementPlan`
- `CultivationRegistration`
- `FarmingCommitment`
- `WarehouseInboundRequest`
The refactoring is focused on improving consistency, readability, and maintainability across entity configurations and their SQL representations.
---
- Updated EF Core model configurations for all four entities.
- Normalized column names and types to match SQL standards.
- Applied consistent naming conventions and structure across related files.
- Removed redundant properties and improved annotation usage.
- Cleaned up related repositories and view models (if applicable).
---
- Verified model changes via local database migrations.
- Ensured existing unit tests (if any) pass.
- Confirmed no …

refactor(SQL) Refactor ProcurementPlan, CultivationRegistration, FarmingCommitment, WarehouseInboundRequest tables

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmerController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmerDTOs/FarmerViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IFarmerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmerService.cs

This pull request introduces a new API endpoint to retrieve a list of all farmers in the system. The API serves as a foundational feature for modules that require farmer data, such as cultivation registration, reporting, or dashboard displays.
---
- **HTTP Method:** `GET`
- **Route:** `/api/farmers`
- **Response:**
- Returns an array of farmer objects, each containing:
- Farmer ID
- Name
- Identification number
- Contact details
- Associated cooperative (if any)
---
- Added repository method to query all farmers from the database.
- Implemented service layer to encapsulate retrieval logic.
- Created controller action to expose API endpoint.
- Applied pagination and optional filtering logic (if applicable).
- Ensured output model adheres to expected frontend structure.
---
- ✅ Tested with …

feat(Farmer) Implement Get all farmer API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmingCommitmentController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IFarmingCommitmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs

This pull request adds a new API endpoint that allows clients to retrieve detailed information for a specific farming commitment by its unique identifier. This endpoint is useful for viewing or editing commitment data in admin panels or detail views.
---
- **HTTP Method:** `GET`
- **Route:** `/api/farming-commitments/{id}`
- **Path Parameter:**
- `id` (GUID or int): Unique identifier of the farming commitment
- **Response:**
- **200 OK**: Returns full details of the farming commitment
- **404 Not Found**: If the specified ID does not exist
- **400 Bad Request**: If the ID format is invalid
---
- Added repository method to fetch farming commitment by ID
- Created service logic to handle null cases and prepare response DTO
- Implemented controller action to expose the endpoint
- Added …

feat(FarmingCommitment) Implement Get by Id Farming commitments  API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonDetailController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/InventoryController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingStageController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseOutboundReceiptController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseOutboundRequestsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseReceiptsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehousesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/CropSeasonDetail.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/Inventory.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/ProcessingBatch.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/ProcessingBatchProgress.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/ProcessingParameter.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/ProcessingStage.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/Warehouse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/WarehouseOutboundReceipt.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/WarehouseOutboundRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/WarehouseReceipt.cs

Enhance the querying capability of multiple `GetAll` endpoints by integrating OData. This allows clients to filter, sort, and paginate data efficiently via query strings. Affects key data entities related to warehouse, inventory, processing, and crop season workflows.
---
- Integrated `ODataQueryOptions<T>` into GetAll endpoints of multiple controllers
- Added `[EnableQuery]` attributes for filtering, ordering, and paging support
- Updated repository models if needed for compatibility with OData (e.g., navigation properties)
- Registered OData services in `Program.cs` for global enablement
---
- `CropSeasonDetailController.cs`
- `InventoryController.cs`
- `ProcessingBatchsController.cs`
- `ProcessingBatchsProgressController.cs`
- `ProcessingParametersController.cs`
- …

feat(odata): integrate OData support into GetAll APIs for remaining entities

---

Database/DakLakCoffee_SCM.sql
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryItem/ContractDeliveryItemCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IContractDeliveryItemRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ContractDeliveryItemRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs

Implement the API to allow BusinessManager or BusinessStaff to create a new delivery item for a specific delivery batch in a contract. This feature ensures quantity constraints, prevents duplicates, and generates unique codes per item.
---
- Implemented `CreateContractDeliveryItemAsync` endpoint with role-based access
- Added service logic with full validation: 
- contract item belongs to the contract
- planned quantity must not exceed remaining contract quantity
- no duplicate coffee type in the same batch
- Auto-generate `DeliveryItemCode` based on delivery batch code and item index
- Map `CreateDto → Entity` and `Entity → ViewDto`
- Added custom Vietnamese validation messages
---
- `ContractDeliveryItemsController.cs`
- …

feat(contract-delivery-item): implement create API with validation, duplicate check, code generation, and response mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessStaffController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseInboundRequestsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessStaffDTOs/BusinessStaffCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IBusinessStaffRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/BusinessStaffRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessStaffService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessStaffMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessStaffService.cs

☕ Feature: BusinessStaff – Create Staff for BusinessManager (API)
📌 Objective
Implement a new API that allows BusinessManager users to create new BusinessStaff accounts under their supervision. This feature simplifies staff onboarding and ensures appropriate role and warehouse assignment.
✅ Key Changes
Added new API endpoint POST /api/businessstaffs for staff creation
Implemented service logic in BusinessStaffService.cs with validation, role checking, and password hashing
Mapped BusinessStaffCreateDto to entity and ensured DB persistence
Set up default status as active and email verification as true for internal accounts
🧱 Affected Files
BusinessStaffsController.cs
BusinessStaffService.cs
IBusinessStaffService.cs
BusinessStaffCreateDto.cs
BusinessStaffMapper.cs
📁 Added
BusinessStaff …

feat(businessStaff): add create new staff feature for manager

---

Database/DakLakCoffee_SCM.sql

Add sample SQL insert statements to support testing and data seeding for core warehouse-related entities. This includes inbound requests, warehouse receipts, inventory tracking, and inventory change logs. It supports flow testing by BusinessManager and WarehouseStaff roles.
---
- Added SQL inserts for `WarehouseInboundRequests`, `WarehouseReceipts`, `Inventories`, and `InventoryLogs`
- Ensured entity relationship integrity across foreign keys (Batch, Warehouse, Staff, Farmer)
- Set realistic values for quantity, status (`completed`), and timestamps for traceability
---
- `DakLakCoffee_SCM.sql`
---
- SQL insert logic for:
- Inbound requests (`INREQ-2025-0001`)
- Receipts (`RECEIPT-2025-0001`)
- Inventories (`INV-2025-0001`)
- Inventory logs (`increase` entry)
---
1. Open SQL Server …

feat(seed): insert sample data for inbound requests, receipts, inventories, and inventory logs

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

Cập nhật tiến độ sơ chế của một `ProcessingBatchProgress`. Sau khi cập nhật thành công, API sẽ trả về thông tin chi tiết của tiến độ đó (bao gồm stage, batch, updatedBy và parameters).
---
- Sửa `UpdateAsync` trong `ProcessingBatchProgressService` để trả về `ProcessingBatchProgressDetailDto`
- Gọi lại `GetByIdAsync` để lấy đầy đủ thông tin liên quan (stage, batch, updatedBy)
- Trả về `200 OK` + `result.Data` thay vì `204 No Content`
- Fix lỗi trùng tên biến `dto` gây ra `CS0136`
---
- `ProcessingBatchProgressMapper.cs`
- `IProcessingBatchProgressRepository.cs`
---
- Không thêm file mới
---
1. **Login** với vai trò `Farmer` hoặc `Expert` để lấy JWT token
- `PUT …

feat(processing-progress): Update processingbatchsprogress

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchProgressRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

Add **Hard Delete** functionality to the `ProcessingBatchProgress` table, allowing permanent deletion of a record from the database.  
Handles safety by checking record existence and catching exceptions related to foreign key constraints.
---
- Added `HardDeleteAsync(Guid)` method in `ProcessingBatchProgressService`
- Declared method in `IProcessingBatchProgressService` interface
- Added API endpoint: `DELETE /api/ProcessingBatchsProgress/hard/{id}`
- Catches and returns `DbUpdateException` if there are related records (e.g., `ProcessingParameter`, `ProcessingBatchWaste`)
- Returns meaningful messages to frontend when deletion is blocked
---
---
- `HardDeleteAsync(Guid …

 feat(ProcessingBatchProgress): implement Hard Delete function

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

Refactor `ProductService` to improve access control logic and display clarity. Ensure that only non-deleted managers and staff can access product data, and include `ApprovedBy` user name in the response for approved products.
---
- ✅ Added `.Include(p => p.ApprovedByNavigation)` to load approver name into `ApprovedByName` field  
- ✅ Applied `!m.IsDeleted` and `!s.IsDeleted` checks for both `BusinessManager` and `BusinessStaff`  
- ✅ Ensured stricter filtering logic during product access to prevent exposure of deleted users' data
---
- `ProductService.cs`  
---
---
1. **Login** with role `BusinessManager` or assigned `BusinessStaff`  
2. Send request:
- `GET /api/products/{productId}`
3. **Expected:**
- Response contains …

refactor(product): add ApprovedBy include and apply IsDeleted filters for access checks

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/RoleService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs

Improve readability and maintainability of `RoleService` and `UserAccountService` by applying consistent code formatting. This change does **not** alter any business logic or service behavior.
---
- ✅ Reorganized method and property formatting for better structure  
- ✅ Standardized spacing, indentation, and grouping of related logic  
- ✅ Removed unused using directives (if any) and ensured consistent coding style
---
- `RoleService.cs`  
- `UserAccountService.cs`
---
---
This is a formatting-only refactor, so functional testing is not required.  
However, you can validate indirectly by:
1. Ensuring build succeeds without issues  
2. Running existing unit tests or integration tests to verify no regression
---
---
- No backend behavior, endpoints, or DB queries …

style(service): reformat RoleService and UserAccountService for readability

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/InventoryController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseReceiptsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehousesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/InventoryLogDTOs/InventoryLogDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IInventoryRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/InventoryRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IInventoryService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseReceiptService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseReceiptService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseService.cs

☕ Feature: Company-based Access Control for Inventory Modules
📌 Objective
Implement access restrictions across inventory-related modules to ensure BusinessManager and BusinessStaff can only view or act upon data within their company.
✅ Key Changes
🔐 Inventory: Validated warehouse ownership using userId to ensure inventory actions belong to the correct company
📦 Warehouse: Filtered GetAll API to return only warehouses owned by the user's company
📄 Warehouse Receipt: Validated the warehouse ownership before creating or confirming a receipt
🧾 General: Passed userId from token into service layers to consistently enforce access boundaries
🧱 Affected Files
InventoryService.cs
WarehouseService.cs
WarehouseReceiptService.cs
IInventoryService.cs, IWarehouseService.cs, IWarehouseReceiptService.cs …

feat(role4): restrict access and creation by user ownership

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

Implement the `Update Product` API to allow **BusinessManager** or **BusinessStaff** (under the same supervisor) to update product information with validation, permission check, and ownership enforcement.
---
- Implemented `PUT /api/products/{productId}` endpoint in `ProductsController`
- Added business logic in `ProductService.Update()` with manager/staff role validation
- Checked foreign key references (batch, inventory, coffee type) before update
- Applied `ProductUpdateDto` with full validation using `IValidatableObject`
- Used `MapToUpdateProduct()` mapper for clean entity update logic
---
- `ProductsController.cs`
- `IProductService.cs`
- `ProductMapper.cs`
---
- `ProductUpdateDto.cs`
---
1. **Login** with a valid `BusinessManager` or `BusinessStaff` account to …

feat(product): implement Update Product API with validation, permission check, and mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs

Improve the consistency and readability of the business-related service layers by reformatting `BusinessManagerService` and `BusinessBuyerService` without changing business logic. This helps maintain clean code standards and improves maintainability.
---
- Reorganized code structure and indentation in `BusinessManagerService`
- Reformatted method blocks, comments, and spacing in `BusinessBuyerService`
- Ensured method grouping and separation for better readability
- No functional changes or behavior modifications introduced
---
- `BusinessManagerService.cs`
---
- *(No new files were added in this change)*
---
No functional testing required as this PR only contains formatting changes.  
However, to ensure nothing is broken:
1. Run the solution and verify the …

style(service): reformat BusinessManager and BusinessBuyer services for consistency and readability

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProductService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

Secure the `GetById` API of `Product` entity by enforcing user-based access control using `userId` from JWT token.  
Also, rename delete methods to improve clarity and maintain naming consistency across service interfaces.
---
- Refactor `GetById(productId)` to `GetById(productId, userId)` and enforce `CreatedBy == ManagerId` check
- Retrieve `userId` from JWT token inside controller to ensure scoped access
- Rename:
- `DeleteById` → `DeleteProductById`
- `SoftDeleteById` → `SoftDeleteProductById`
---
- `ProductsController.cs`
- `IProductService.cs`
---
- *(No new files added in this PR)*
---
1. **Login** as `BusinessManager` or `BusinessStaff` to retrieve a valid JWT token
2. Test the following endpoints:
- `GET /api/products/{productId}` → Should return product …

refactor(product): secure GetById with user-based access check and rename delete methods for clarity

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IBusinessManagerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessManagerService.cs

Refactor the `GetById` API for `BusinessManager` to enforce role-based access control.  
Admin users can view any manager's profile, while BusinessManagers are restricted to viewing only their own.
---
- Refactored `GetById` API in `BusinessManagersController` to extract `userId` and `role` from token.
- Added permission logic in service layer to block unauthorized access based on role.
- Reused and extended logic from existing claim helpers (`ClaimsHelper.GetUserId()`, `GetRole()`).
- Improved security consistency with other protected APIs in the system.
---
- `BusinessManagersController.cs`
- `IBusinessManagerService.cs`
- `BusinessManagerService.cs`
---
- _No new files were added in this change._
---
1. **Login** using either:
- Role: `Admin` → to view **any** manager’s profile
- Role: …

refactor(business-manager): enforce role-based access in GetById API with self-access check for BusinessManager

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseReceiptsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseReceiptRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseReceiptService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseReceiptService.cs

☕ Feature: WarehouseReceipt – Soft Delete & Hard Delete API
📌 Objective
This PR adds two new backend features that allow authorized users to:
Soft delete a warehouse receipt (logical deletion using IsDeleted = true)
Hard delete a warehouse receipt (permanent deletion from database)
This applies to the BusinessManager, BusinessStaff, and Admin roles in the warehouse operations flow.
✅ Key Changes
Added SoftDeleteAsync and HardDeleteAsync methods in WarehouseReceiptService
Extended IWarehouseReceiptService interface
Added two new API endpoints in WarehouseReceiptsController:
DELETE /api/WarehouseReceipts/{id}/soft
DELETE /api/WarehouseReceipts/{id}/hard
Role-based permission check:
Soft Delete: BusinessStaff, BusinessManager
Hard Delete: Admin only
Updated logic to use only allowed status …

feat(warehouseReceipt): add soft and hard delete

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessBuyerDTOs/BusinessBuyerViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryBatchViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessBuyerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessBuyerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs

Refactor existing ViewDetailDto class names by renaming them to ViewDetailsDto to ensure consistency across DTO layers. This improves naming clarity and follows the plural form used across other view-related DTOs.
---
- Renamed DTO files: `*ViewDetailDto.cs` ➝ `*ViewDetailsDto.cs`
- Updated usages in controllers, services, and mappers to reflect the new naming
- Maintained existing logic — no functional changes introduced
---
- `ContractDeliveryBatchsController.cs`
- `ContractDeliveryBatchService.cs`
- `BusinessBuyerMapper.cs`
- `ContractDeliveryBatchMapper.cs`
---
- `BusinessBuyerViewDetailsDto.cs`
- `ContractViewDetailsDto.cs`
- …

refactor(dto): rename *ViewDetailDto to *ViewDetailsDto for consistency with naming conventions

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ViewDetailsDtos/ProcurementPlanDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

This pull request updates the `Get Procurement Plan by ID` API by modifying the response DTO structure. These changes aim to improve data clarity, consistency, and alignment with frontend requirements or recent database adjustments.
---
- Updated fields in the `ProcurementPlanDetailDto` (or equivalent):
- Renamed/mapped certain properties for better naming consistency
- Added new fields (e.g., status label, associated farmer name)
- Removed unused or redundant fields
- Adjusted data mapping logic in service/controller to reflect the new DTO shape
- Verified compatibility with calling clients (e.g., frontend or external consumers)
---
- ✅ Retrieved procurement plan by valid ID returns new DTO structure
- ✅ Verified backward compatibility or adjusted affected UI as needed
- ✅ Validated null …

refactor(ProcurementPlan) refactor Get Procurement plans by Id API modify some fields in dto

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrdersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Implement the API to retrieve detailed information of a specific order. This includes order metadata, item breakdown, and related contract/delivery batch info in a lightweight, display-oriented format. The endpoint supports both Manager and Staff views.
---
- Implemented `GetById` method in `OrderService`
- Added new DTOs: `OrderViewDetailsDto` and `OrderItemViewDto`
- Included soft-delete filtering on `OrderItems`
- Mapped `ProductName` from navigation property
- Updated `OrdersController` to expose the endpoint
- Ensured enum serialization with `[JsonConverter]` for `OrderStatus`
---
- `IOrderService.cs`
- `OrderMapper.cs`
---
- `OrderViewDetailsDto.cs`
- `OrderItemViewDto.cs`
---
1. **Login** as a `BusinessManager` or `BusinessStaff` to get a …

feat(order): implement GetById API with detail DTO, product mapping, and soft-delete filtering

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Implement the ability for authenticated `Farmer` users to create new `ProcessingBatch` records via API. This supports the core processing workflow from raw input tracking to product generation.
---
- Added `CreateAsync` method in `ProcessingBatchService` with validation and data mapping
- Auto-generate `SystemBatchCode` using `ICodeGenerator` by current year
- Validate related entities: `Farmer`, `CoffeeType`, `CropSeason`, `ProcessingMethod`
- Prevent duplicate `BatchCode` via `AnyAsync` before insert
- Register new `POST /api/ProcessingBatch` endpoint with `[Authorize(Roles = "Farmer")]`
- Fixed potential EF Core concurrency issue by removing parallel queries
---
- `IProcessingBatchService.cs`
- `ProcessingBatchController.cs`
- `ProcessingBatchCreateDto.cs` …

feat: implement ProcessingBatch creation API for farmers

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/InventoryLogsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IInventoryLogService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryLogService.cs

☕ Feature: InventoryLog Deletion API (Soft + Hard)
📌 Objective
Add support for both soft delete and hard delete operations for inventory logs. This feature ensures better data management, allowing temporary hiding (soft delete) or permanent removal (hard delete) of inventory log records. Applicable to roles like BusinessManager and Admin.
✅ Key Changes
Implemented SoftDeleteAsync and HardDeleteAsync methods in InventoryLogService.
Added endpoints to InventoryLogsController to expose delete APIs.
Added role-based access control:
Soft delete: BusinessManager, Admin
Hard delete: Admin only.
Updated GetAllAsync logic to exclude soft-deleted logs from listing.
Added IsDeleted property to InventoryLog entity (if not already present in database).
🧱 Affected Files
InventoryLogService.cs …

feat(inventorylogs): implement soft and hard delete API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingWasteController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWastesDTOs/ProcessingWasteCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IProcessingBatchWasteRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingBatchWasteRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingWasteService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchWasteMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingWasteService.cs

Implement the `CreateAsync` API to allow farmers to submit new waste records linked to their processing progress.
- Auto-generate `WasteCode` using `ICodeGenerator`
- Validate ownership of `ProgressId` for the authenticated farmer
---
- ✨ Implemented `CreateAsync(ProcessingWasteCreateDto dto, Guid userId, bool isAdmin)` in `ProcessingWasteService`
- 🔐 Role check: only `Farmer` can create waste for their own batches
- 🧠 Validation: ensure `ProgressId` belongs to the farmer
- 🆔 Used `ICodeGenerator` to generate unique `WasteCode`
- 💾 Save waste entity with metadata (`CreatedAt`, `RecordedBy`)
- 📡 Expose API via controller: `POST /api/processingwaste`
---
- `ProcessingWasteService.cs`
- `IProcessingWasteService.cs`
- `ProcessingWasteController.cs`
- `ProcessingWasteCreateDto.cs`
- …

feat(api): implement Create API for ProcessingWaste (Farmer/Admin)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrderItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderItemService.cs

Implement a new API to perform hard deletion of an `OrderItem`, including business validation and proper response handling. Additionally, fix incorrect logic related to `IsDeleted` check in `ContractDeliveryItem` hard deletion flow.
---
- Implemented `DELETE /api/OrderItems/{orderItemId}` in `OrderItemsController`
- Created `DeleteOrderItemById` method in `OrderItemService` with repository access
- Fixed misuse of `!IsDeleted` condition in hard delete of ContractDeliveryItem
- Handled responses for not found, failed deletion, and exceptions consistently
- Updated related interface `IOrderItemService`
---
- `OrderItemService.cs`
- `IOrderItemService.cs`
---
- *(No new files added in this commit)*
---
1. **Login** as a …

feat(order-item): implement hard delete API and fix invalid IsDeleted check in contract-delivery-item

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs

Add permission check for `BusinessManager` role when creating a new `ContractItem`.  
Ensure the `userId` is extracted from JWT and validated to align with the scoped access control applied in Delete and SoftDelete APIs.
---
- Refactored `CreateContractItemAsync` in `ContractItemsController` to extract `userId` from token  
- Updated `IContractItemService` and `ContractItemService` to accept and validate `userId`  
- Checked `BusinessManager` existence before allowing contract item creation  
- Preserved existing validations (duplicate item, contract existence, etc.)
---
- `IContractItemService.cs`
---
---
1. **Login** with a valid `BusinessManager` account to obtain a JWT token
2. Send a request to:
- …

refactor(contract-item): enforce scoped creation permission for BusinessManager in Create API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs

Enforce scoped access control for the `UpdateContractItemAsync` API.  
Ensure that only authenticated `BusinessManager` users can perform update operations on `ContractItem`, following the same logic as Create/Delete APIs.
---
- Refactored `UpdateContractItemAsync` in controller to extract `userId` from JWT claims
- Updated `IContractItemService` and `ContractItemService` to accept and validate `userId`
- Checked `BusinessManager` existence before allowing update execution
- Ensured `IsDeleted` is filtered when retrieving updated item
- Preserved duplicate check and business validation logic
---
- `IContractItemService.cs`
---
---
1. **Login** using a valid `BusinessManager` account to obtain JWT token
2. …

refactor(contract-item): enforce scoped update permission for BusinessManager in Update API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs

Refactor the existing `DELETE /api/contractdeliveryitems/{deliveryItemId}` API to enforce **scoped deletion permission** for `BusinessManager` roles.  
Ensures that only items under contracts belonging to the current manager or their supervised staff can be deleted.
---
- Refactored `ContractDeliveryItemService.DeleteContractDeliveryItemById` with **SellerId ownership check**
- Updated controller to return status via `switch expression` for better readability
- Enhanced service to resolve `ManagerId` or `SupervisorId` from `userId`
- Included EF navigation loading: `ContractItem → Contract` for permission verification
---
- `ContractDeliveryItemsController.cs`
- `IContractDeliveryItemService.cs`
---
- *(None)* – this is a pure refactor and permission …

refactor(contract-delivery-item): enforce scoped deletion permission for BusinessManager in Delete API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessBuyersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessManagersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrderItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrdersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProductsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/RolesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UserAccountsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IRoleService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IUserAccountService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/RoleService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UserAccountService.cs

Reformat controller and service classes for better readability, consistent layout, and standardized structure.  
This cleanup improves code maintainability across modules such as `Contract`, `Order`, `Product`, `UserAccount`, etc.
---
- Reorganized spacing, line breaks, and indentation for controller methods  
- Normalized attribute alignment (`[Authorize]`, `[HttpGet]`, etc.) across endpoints  
- Applied consistent structure to service interfaces and implementations  
- Ensured consistent naming, access modifiers, and method signatures across affected files  
---
- `BusinessManagersController.cs`
- `ContractDeliveryBatchsController.cs`
- …

style(controller, service): reformat code for consistency and readability across maintained modules

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrderItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderItemService.cs

Refactor the OrderItem Update API to strictly enforce scoped permissions based on the current user's `userId`, ensuring only valid BusinessManager or BusinessStaff can update. Add validation for quantity constraints and enhance consistency in business rules.
---
- 🔐 Added scoped permission check by resolving `managerId` from `userId`
- ✅ Validated quantity against `PlannedQuantity` of the ContractDeliveryItem
- 🚫 Prevented duplicate OrderItems with same Product in the same delivery
- 💰 Auto-infer UnitPrice & DiscountAmount if not provided
- 🔁 Refactored update flow to map DTO → entity with consistency
---
- `OrderItemService.cs`
- `IOrderItemService.cs`
---
- N/A
---
1. **Login** using a valid `BusinessManager` or `BusinessStaff` account to get token
2. Send …

refactor(order-item): enforce scoped update with userId-based manager verification and quantity validation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Cập nhật logic lọc dữ liệu theo vai trò người dùng khi truy vấn danh sách ProcessingBatch và ProcessingBatchProgress.
---
- 🎯 Áp dụng phân quyền cho `GetAllByUserId`:
- **Admin**: xem toàn bộ batch và progress.
- **BusinessManager**: chỉ xem batch/progress thuộc mùa vụ do mình duyệt (`Commitment.ApprovedBy`).
- **Farmer**: chỉ xem batch/progress mình sở hữu.
- ✅ Xử lý `return` thông báo rõ ràng nếu người dùng không có quyền truy cập hoặc không có dữ liệu.
- 🔄 Refactor `Mapper` để hỗ trợ mapping `StageName`, `BatchCode`... mà không cần navigation phức tạp.
- 🚫 Không chỉnh sửa hoặc thêm mới bất kỳ bảng nào trong CSDL.
---
- `ProcessingBatchesController.cs`
- …

✨ Update role-based access for ProcessingBatch & Progress: validate BM, Admin, Farmer; improve DTO mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Fix the soft delete logic for `Contract`, `ContractDeliveryBatch`, and `Order` services by ensuring already-deleted child items are skipped to avoid redundant updates and potential state inconsistencies. This improves data integrity and performance during cascading deletion processes for BusinessManager roles.
---
- Refactored `SoftDelete` logic in `ContractService`, `OrderService`, and `ContractDeliveryBatchService`
- Added `IsDeleted` check to skip child entities that were already soft-deleted
- Ensured `UpdatedAt` is only modified for active records
- Reduced unnecessary EF update calls for deleted records
---
- `ContractDeliveryBatchService.cs`
---
- _No new files added_
---
1. **Login** as a `BusinessManager` to retrieve JWT token
2. Use the …

fix(soft-delete): prevent redundant update on already deleted child items in ContractService, OrderService, and ContractDeliveryBatchService

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/InventoryLogsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/InventoryLogDTOs/InventoryLogDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/InventoryLogDTOs/InventoryLogListItemDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IInventoryLogRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/InventoryLogRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IInventoryLogService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/InventoryLogMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryLogService.cs

✨ Feature: [InventoryLogs] – View Inventory Log by LogId
📌 Purpose
Support retrieving detailed InventoryLog data by LogId, including related entities (Inventory, Warehouse, Batch, CoffeeType, Farmer, etc.) for detail view.
✅ Key Changes
Added new service method: GetByIdAsync(logId, userId)
Implemented access control to ensure BusinessManager or Staff can only access logs related to their own company
Loaded all necessary navigation properties (includes) in InventoryLogRepository.GetByIdWithAllRelationsAsync
Created mapping method ToByLogIdDto to map entity to DTO
Returned detail log data with full relation chain (for UI detail page)
📁 Affected Files
InventoryLogsController.cs
InventoryLogService.cs
InventoryLogRepository.cs
InventoryLogMapper.cs
InventoryLogByLogIdDto.cs (new or updated …

feat(inventorylogs):Implement view detail with logID

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Update filtering logic for Business Managers. The `ApprovedBy` field in `FarmingCommitments` stores the **ManagerId** (not the UserId), so we must map UserId → ManagerId before applying access restrictions.
---
- Retrieve `BusinessManagerId` from `UserId` before filtering
- Update condition to: `Commitment.ApprovedBy == ManagerId` instead of `UserId`
- Return appropriate error if BM is not assigned to any commitment
- Refactor `GetAllByUserId` logic in both `ProcessingBatchService` and `ProcessingBatchProgressService`
---
- `BusinessManagerRepository.cs`
- `IBusinessManagerRepository.cs`
---
- Helper to fetch `BusinessManagerId` using `UserId` (if applicable)
---
1. **Login** as a `BusinessManager` with an assigned …

Update BM logic to filter batches/progress via ManagerId from ApprovedBy"

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProductService.cs

Allow `BusinessStaff` to update products that belong to their enterprise (supervised by the same `BusinessManager`), not just ones directly created by themselves. This ensures role-based control aligns with real-world enterprise structure.
---
- ♻️ Refactored `Update` method in `ProductService` to determine valid `UserId`s from both `BusinessManager` and `BusinessStaff` under the same enterprise
- ✅ Enforced update permission only for users whose `CreatedBy` is in the enterprise-wide list
- 🔍 Removed inefficient per-user loop and replaced with direct batch queries for better performance
---
---
---
1. **Login** as a `BusinessStaff` or `BusinessManager` to retrieve JWT token
2. Send request to:
- `PUT /api/products/update`
- Header: …

refactor(product): enforce scoped update for BusinessStaff using enterprise-wide user list

---

Database/DakLakCoffee_SCM.sql

- Implement the Farming Commitment Details table to store and manage detailed information about farming commitments.
- Define schema with relevant fields such as `commitment ID`, `farmer ID`, `crop type`, `commitment quantity`, `start date`, and `end date`.
- Ensure proper indexing for efficient querying and data retrieval.
- Establish relationships with related tables to maintain data consistency.
- Prepare the table for integration with APIs and frontend components for managing farming commitments.

feat(sql) implement Farming commitment details table

---

Database/DakLakCoffee_SCM.sql

Refactor and correct the SQL table definition for `CropSeasonDetails` to ensure accurate database relationships and constraint logic. This aligns with the updated schema design discussed in the team’s recent model review.
---
- Fixed foreign key and uniqueness constraint definitions in `CropSeasonDetails`
- Removed commented/unused fields to improve readability
- Reformatted the SQL script for consistency across table definitions
---
- `DakLakCoffee_SCM.sql`
---
- _No new files added_
---
1. Pull the latest `PhucLH` branch  
2. Run the updated SQL script to recreate the schema:
- Backup current DB if necessary
- Run `Database/DakLakCoffee_SCM.sql` on local SQL Server
3. Verify that `CropSeasonDetails` table reflects the corrected relationships and no constraint errors are raised during …

chore(schema): fix CropSeasonDetails table constraints and reformat SQL script

---

Database/DakLakCoffee_SCM.sql

Add meaningful test/demo data for newly created shipment-related modules (`Shipments`, `ShipmentDetails`, and `OrderComplaints`) to support backend testing and frontend integration in DakLak Coffee SCM system.
---
- Added SQL `INSERT` statements using `DECLARE` for:
- `Shipments`: creating a delivery record linked to an order and delivery staff
- `ShipmentDetails`: specify products delivered in a shipment
- `OrderComplaints`: simulate complaint with resolution steps and links to evidence
- Used existing `UserAccounts`, `Orders`, `OrderItems`, `BusinessBuyers`, `BusinessManagers` for realistic linkage
- Applied `NEWID()` and `SELECT TOP 1` to fetch required foreign keys dynamically
---
---
- SQL data seeding block (approx. 67 LOC)
---
1. Open `SSMS` or any …

feat(seed): add sample data for Shipments, ShipmentDetails, and OrderComplaints

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentsDetailsDTOs/FarmingCommitmentsDetailsViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

- Refactor the GET method APIs for both Procurement Plan and Farming Commitment modules.
- Improve code readability and maintainability by consolidating shared logic where possible.
- Optimize data retrieval queries for better performance and consistency across both APIs.
- Standardize response formats and enhance error handling to provide clear feedback to clients.
- Ensure thorough validation of input parameters to prevent invalid requests.
- Maintain backward compatibility while implementing improvements.

refactor(Procurement plan, Farming commitment) Refactor GET method APIs for Procurement plan and Farming Commitment

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/OrdersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IOrderRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/OrderRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IOrderService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Implement the Order creation feature, allowing BusinessManager and BusinessStaff to create a new Order with associated OrderItems under a specific ContractDeliveryBatch. Includes validation, mapping, and business constraints.
---
- Implemented `Create` API in `OrdersController` and `OrderService`
- Added `OrderCreateDto` with IValidatableObject validation logic
- Auto-generated `OrderCode` using `CodeGenerator`
- Handled business rules: 1 order per delivery batch, date constraints
- Mapped DTO → Entity with nested `OrderItems`
- Set default OrderDate and calculated TotalAmount
---
- `OrderRepository.cs`
- `IOrderRepository.cs`
- `ICodeGenerator.cs`, `CodeGenerator.cs`
- `OrderMapper.cs`, `OrderItemMapper.cs`
---
- `OrderCreateDto.cs`
---
1. …

feat(order): implement Create Order API with OrderItems, validation, mapping, and business rules

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/ProcurementPlanEnums/ProcurementPlanStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

- Refactor the Update Procurement Plan Status API to improve code structure and maintainability.
- Enhance validation logic to ensure valid status transitions and prevent invalid updates.
- Optimize error handling and provide clearer, more consistent response messages.
- Streamline data processing to improve the API’s performance and reliability.
- Ensure backward compatibility with existing clients while applying improvements.

refactor(Procurement plan) Refactor Update procurement plan status API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentsDetailsDTOs/FarmingCommitmentsDetailsCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ProcurementPlanCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/GenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/IGenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs

- Refactor the Create New Farming Commitment API to improve code structure and readability.
- Enhance input validation to ensure all required fields are correctly provided.
- Optimize data processing logic for better performance and reliability.
- Improve error handling to provide clear and consistent feedback on failure cases.
- Ensure the API maintains backward compatibility with existing clients.
- Increase maintainability and prepare the codebase for future extensions or modifications.

refactor(Farming commitment) refactor Create new Farming commitment API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CultivationRegistrationController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationCreateViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICultivationRegistrationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CultivationRegistrationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CultivationRegistrationService.cs

- Refactor the Create New Cultivation Registration API to improve code clarity and maintainability.
- Enhance input validation to ensure all required fields are correctly provided and valid.
- Optimize data processing logic for better performance and accuracy.
- Improve error handling by providing clear and consistent feedback on failure cases.
- Ensure backward compatibility with existing clients and smooth integration within the system.
- Increase code maintainability to facilitate future enhancements and modifications.

refactor(Cultivation registration) Refactor Create new Cultivation registration API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/ShipmentEnums/ShipmentDeliveryStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/Shipment.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Implement the API for retrieving all shipments associated with orders under contract batches. This feature supports roles like `BusinessManager`, `BusinessStaff`, and `DeliveryStaff` and is part of the logistics and delivery workflow.
---
- Implemented `GetAllShipmentsAsync` API in `ShipmentsController`
- Added service logic in `ShipmentService` with role-based data filtering
- Created mapping logic in `ShipmentMapper` to convert entities to DTOs
- Defined `ShipmentViewAllDto` with enum handling and timestamp support
- Registered `ShipmentRepository` in `UnitOfWork`
---
- `ShipmentMapper.cs`
- `Shipment.cs` (model updated if needed)
- `IUnitOfWork.cs`
- `UnitOfWork.cs`
---
- `ShipmentViewAllDto.cs`
- …

feat(shipment): implement GetAll API with full module (controller, service, mapper, DTO, repo)

---

Database/DakLakCoffee_SCM.sql

Add the new role `DeliveryStaff` to the Roles table and insert a sample user into `UserAccounts` for testing shipment-related APIs and role-based access control. This supports development and testing of delivery staff functionalities.
---
- Insert new role `DeliveryStaff` with description into `Roles` table
- Add a sample DeliveryStaff user with basic information (email, phone, address, hashed password)
- Update seed SQL file `DakLakCoffee_SCM.sql` accordingly
---
---
- N/A (SQL script only updated)
---
1. Open SQL Server Management Studio or any DB tool
2. Run the updated `DakLakCoffee_SCM.sql` to seed Roles and Users
3. Verify that:
- `Roles` table contains `DeliveryStaff` with appropriate ID
- `UserAccounts` has a record with role = `DeliveryStaff`
4. …

feat(seed): add DeliveryStaff role and sample user to database script

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentDetailDTOs/ShipmentDetailViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/OrderMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Implement the `GetById` API for Shipments, allowing authorized roles to retrieve full shipment details including associated `ShipmentDetails`. This supports view functionality for shipment management by roles such as `BusinessManager`, `BusinessStaff`, and `DeliveryStaff`.
---
- Added new API endpoint `GET /api/shipments/{id}` in `ShipmentsController`
- Implemented `GetById` method in `ShipmentService` with proper navigation includes and filtering
- Created `ShipmentViewDetailsDto` and `ShipmentDetailViewDto` for response structure
- Added mapper method to convert entity to detailed DTO
- Role-based access enabled via `[Authorize(Roles = "...")]`
---
- `ShipmentMapper.cs`
- `OrderMapper.cs` (may be touched for …

feat(shipment): implement GetById API with detail view (DTO, mapper, service, controller)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentDeleteDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Add soft-delete functionality for `Shipment` entities, including cascading soft-delete on related `ShipmentDetails`. This operation is scoped to `BusinessManager` roles and ensures data consistency for historical shipment records.
---
- Implemented `SoftDeleteShipmentById` method in `ShipmentService`
- Added new endpoint: `PATCH /api/shipments/soft-delete/{shipmentId}`
- Applied cascade soft-delete logic for related `ShipmentDetails`
- Updated `UnitOfWork` to include `ShipmentDetailRepository`
- Refined controller logic for proper response codes and messages
---
- `UnitOfWork.cs`
- `IUnitOfWork.cs`
---
- `ShipmentDetailRepository.cs`
- `IShipmentDetailRepository.cs`
- `ShipmentDeleteDto.cs` *(placeholder if needed …

feat(shipment): implement soft-delete API for Shipment and its details with scoped validation and repository update

---

Database/DakLakCoffee_SCM.sql

This PR updates the seed SQL script to:
- Assign a newly added `DeliveryStaff` user to sample `Shipment` records.
- Correct the password hash for the user `BusinessStaff2` to enable login functionality.
These changes ensure proper user-role relationships and support backend authentication testing.
---
- Assigned DeliveryStaff user to relevant `Shipment` entries in the seed script
- Updated the `PasswordHash` of `BusinessStaff2` to a valid hashed string
- Ensured changes do not conflict with recent shipment API functionalities
---
- `DakLakCoffee_SCM.sql` (seed script)
---
- *(None – all changes were updates to existing data)*
---
1. Reseed your database using the updated `DakLakCoffee_SCM.sql` script
2. Verify:
- `BusinessStaff2` can successfully log in with the expected password
- …

fix(seed): update Shipment assignee and BusinessStaff2 password hash in seed script

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentDetailsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentDetailDTOs/ShipmentDetailDeleteDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentDetailService.cs

Implement a soft-delete feature for `ShipmentDetail` entity to allow `BusinessManager` to mark records as deleted instead of permanently removing them. This is part of the Shipment flow and ensures data traceability.
---
- Add `ShipmentDetailsController` with `PATCH /soft-delete/{id}` endpoint
- Implement `ShipmentDetailService` with business logic for soft-delete
- Define `IShipmentDetailService` interface and register it in DI container
- Update `Program.cs` to support service injection
---
- `Program.cs`
---
- `ShipmentDetailDeleteDto.cs` *(placeholder for future extensibility)*
---
1. **Login** as `BusinessManager` to obtain a JWT …

feat(shipment-detail): implement soft-delete API for ShipmentDetail with controller, service, interface, and DI registration

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

This pull request refactors the `GetAll` API for **Shipment** to enforce **data access restrictions** based on the user's role (`BusinessManager`, `BusinessStaff`, or `DeliveryStaff`). It ensures that users only view shipments they are authorized to see, based on contract ownership or assignment.
---
- ♻️ Refactored `ShipmentService.GetAll(Guid userId)` to dynamically resolve role from database and return only allowed shipments
- 🧠 Added role-based query logic for `BusinessManager`, `BusinessStaff` (via `SupervisorId`), and `DeliveryStaff` (via `DeliveryStaffId`)
- 🔐 Ensured controller retrieves `userId` from JWT and passes to service (instead of relying on injected role claims)
- ✅ Updated interface `IShipmentService` and applied clean separation of role-check logic
- 📦 Ensured all …

refactor(shipment): enforce scoped GetAll API by verifying user role and shipment access (manager, staff, delivery)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

This pull request refactors the `GetById` API of the **Shipment** module to enforce strict access control based on user roles. It ensures that only authorized users (BusinessManager, BusinessStaff, DeliveryStaff) can view shipment details that belong to them, either by assignment or contract ownership.
---
- ♻️ Refactored `ShipmentService.GetById(Guid, Guid)` to resolve user role before access evaluation
- 🔐 Added permission check logic for `DeliveryStaff` (via `DeliveryStaffId`) and `BusinessManager/Staff` (via `Contract.SellerId`)
- 🧩 Adjusted controller to retrieve `userId` from JWT and pass into service for verification
- ✅ Ensured output remains in `ShipmentViewDetailsDto` format for consistent frontend integration
---
- …

refactor(shipment): enforce scoped GetById API with role-based access control (manager, staff, delivery)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentDetailsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentDetailDTOs/ShipmentDetailCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentDetailDTOs/ShipmentDetailViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentDetailMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentDetailService.cs

Implement API for creating a ShipmentDetail line item. This feature allows BusinessManagers and BusinessStaff to add shipment details linked to OrderItem, ensuring quantity does not exceed planned value and units match the original product.
---
- Implemented `Create` method in `ShipmentDetailService` with full validation flow
- Applied `ProductUnit` enum for standardizing unit input/output (DTO, mapping, database)
- Verified contract consistency between Order and Shipment via `DeliveryBatch.ContractId`
- Prevented duplicate (ShipmentId + OrderItemId) records in DB
- Added fallback logic for unit parsing based on Product.Unit string
---
- `IShipmentDetailRepository.cs`
- …

feat(shipment-detail): implement Create API with enum-based Unit, contract validation, quantity check, and mapping

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs

Unify unit representation across the system by replacing `string Unit` with strongly typed `ProductUnit` enum in `ProductViewAllDto`, `ProductViewDetailsDto`, and `ProcessingBatch` mapping.
---
- Update `ProductViewAllDto` and `ProductViewDetailsDto` to use `ProductUnit` enum
- Refactor `ProcessingBatchMapper` to parse `Product.Unit` from string to enum
- Add fallback to `ProductUnit.Kg` when parsing fails
- Ensure consistency across all product-related outputs
---
- `ProductViewAllDto.cs`
- `ProductViewDetailsDto.cs`
- `ProductMapper.cs`
- `ProcessingBatchMapper.cs`
---
1. Truy xuất danh sách product hoặc chi tiết `ProcessingBatch`
2. Đảm bảo `Unit` trong phản hồi JSON là dạng chuỗi enum (e.g., `"Kg"`, `"Tan"`, ...)
3. Kiểm tra tương thích frontend không bị lỗi khi dùng enum
---
---
- …

refactor(product): apply ProductUnit enum in ProductView DTOs and ProcessingBatch mapper for consistency

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CultivationRegistrationController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationCreateViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewAllAvailableDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICultivationRegistrationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CultivationRegistrationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CultivationRegistrationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

- Refactor the View Detail and Create New Cultivation Registration APIs to improve code clarity and maintainability.
- Enhance input validation and error handling for both viewing details and creating new records.
- Optimize data retrieval and processing logic to ensure accurate and efficient operations.
- Standardize response formats for better consistency across APIs.
- Ensure backward compatibility with existing clients while applying improvements.
- Prepare the codebase for easier future enhancements and extensions.

refactor(Cultivation registration) Refactor View detail and Create new Cultivation registration API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentDetailsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentDetailService.cs

Enhance the soft-delete logic of `ShipmentDetail` to ensure that only the appropriate `BusinessManager` associated with the seller of the contract can delete related shipment details. This adds a layer of role-based access control and enterprise-level data integrity.
---
- Refactored `SoftDeleteShipmentDetailById` service method to include seller verification via manager's `UserId`
- Added query condition: check `Contract.SellerId == manager.ManagerId`
- Ensured that only shipment details under contracts of the manager’s enterprise can be deleted
- Maintained existing deletion timestamp and IsDeleted flag logic
---
---
- *(None for this task)*
---
1. **Login** using `BusinessManager` credentials to …

refactor(shipment-detail): enforce scoped soft-delete by verifying seller via manager userId

---

Database/DakLakCoffee_SCM.sql

Seed official demo data for use in the group’s capstone project presentation. The data supports flows related to BusinessManager creating contracts with BusinessBuyers and viewing contract items in the demo system.
---
- Inserted 4 new `BusinessBuyers` with full company and contact details
- Added 3 `Contracts` linked to existing seller and new buyers
- Completed seeding `ContractItems` to ensure at least 15 rows in total across the new contracts
- Queried existing CoffeeTypes and referenced them in seed
- Ensured datetime fields (`CreatedAt`, `UpdatedAt`, `SignedAt`) are set dynamically via `GETDATE()`
---
- `SeedData_BusinessBuyers.sql`
- `SeedData_Contracts.sql`
- `SeedData_ContractItems.sql`
- (No C# files affected – SQL-level data seed only)
---
- `SeedData_Contract_Demo2025.sql` …

feat(seed): insert 4 BusinessBuyers, 3 Contracts, and complete 15 ContractItems for demo

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Enhance the `Order` module by restructuring the core APIs to enforce role-based validation and ensure that only the owning `BusinessManager` or assigned `BusinessStaff` can perform create, update, delete, or soft-delete operations. Introduce better quantity constraint logic and ensure consistent data validation.
---
- Refactor Create API: verify `BusinessManager` ownership and validate `OrderItems` quantity rules
- Refactor Update API: ensure only allowed roles can modify and properly update nested `OrderItems`
- Refactor Delete & SoftDelete: enforce scoped permission based on `SellerId` and user role
- Add internal helper methods to simplify `UserId` → `SellerId` resolution for validation
- Improve error responses for unauthorized or invalid operations
---
- …

refactor(order): restructure Create/Update/Delete/SoftDelete APIs to improve role-based validation and quantity constraint logic

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CultivationRegistrationController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationUpdateStatusDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/CultivationRegistrationEnums/CultivationRegistrationStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICultivationRegistrationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CultivationRegistrationService.cs

- Implement the Update Cultivation Registration Status API to allow modification of the status of existing cultivation registrations.
- Support updating the `status` field with proper validation of allowed status values.
- Ensure correct handling of state transitions to prevent invalid or inconsistent status changes.
- Provide clear and consistent responses including success confirmation and error messages.
- Enhance the API's performance, reliability, and maintainability.
- Maintain backward compatibility with existing clients while applying improvements.

feat(Cultivation registration) Implement Update Cultivation registration status API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Implement API for creating new Shipments by Business Managers, including quantity validation against OrderItem limits and proper entity mapping. Ensure business rules are respected for shipment creation flow.
---
- Implemented `CreateShipmentAsync` service method and API controller.
- Added quantity validation to prevent over-shipment per `OrderItem`.
- Applied mapping between `CreateShipmentDto` and domain model.
- Integrated role-based access control and order ownership check.
---
- `ShipmentController.cs`
- `CreateShipmentDto.cs`
- `ShipmentMapper.cs`
---
- `CreateShipmentDto.cs`
- `ShipmentMapper.cs`
---
1. **Sign in** as a `BusinessManager` to obtain a JWT token.
2. Send a POST request to:
- `POST /api/shipments`
- Header: …

feat(shipment): implement Create Shipment API with validation, quantity check, and mapping rules

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingParametersController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingWasteController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingWasteDisposalController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/PayOSWebhookDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/PaymentCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/PaymentResponseDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWasteDisposalDTOs/ProcessingWasteDisposalCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWasteDisposalDTOs/ProcessingWasteDisposalUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWasteDisposalDTOs/ProcessingWasteDisposalViewByIdDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/PaymentEnums/PaymentStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/ICodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingWasteDisposalService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingWasteDisposalMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingWasteDisposalService.cs

Implement full CRUD functionality for **Processing Waste Disposal** module, including role-based permission checks (Farmer and BusinessManager). This supports better waste tracking and enhances data management for the farming process.
---
- Implement `Create`, `GetAll`, `GetById`, `Update`, `SoftDelete`, and `HardDelete` APIs  
- Add service and repository logic for `ProcessingWasteDisposal`  
- Add permission checking for roles: `Farmer`, `BusinessManager`, with linked `FarmingCommitment`  
- Add DTOs: `CreateDto`, `UpdateDto`, `ViewDto`  
- Validation, auto-gen disposal code, error handling  
---
- `ProcessingWasteDisposalService.cs`  
- `IProcessingWasteDisposalService.cs`  
- `ProcessingWasteDisposalController.cs`  
- `ProcessingWasteDisposalRepository.cs`  
- …

 "feat: implement CRUD API for Processing Waste Disposal with role-based permissions (Farmer & BusinessManager)"

---

Database/DakLakCoffee_SCM.sql

Add seed data for delivery batches and delivery items associated with Contract CTR-2025-0002, CTR-2025-0003, and CTR-2025-0004.  
This aims to support graduation demo and testing shipment flows based on real contract delivery structure.
---
- Added 3 `ContractDeliveryBatches` for each contract (multi-round deliveries for CTR-0002/0003, single-round for CTR-0004)
- Inserted `ContractDeliveryItems` mapping specific coffee types (Washed, Robusta, Culi, etc.) to each batch
- Ensured consistency with previous seed structure and respected foreign key constraints
---
---
- New `INSERT` blocks for:
- `ContractDeliveryBatches`
- `ContractDeliveryItems`
---
1. Open SQL Server Management Studio (or Azure Data Studio)
2. Run the updated script: …

feat(seed): add ContractDeliveryBatches and DeliveryItems for Contracts 002–004

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ShipmentDTOs/ShipmentUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentDetailRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ShipmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Implement the `PUT /api/shipments/{shipmentId}` API to allow BusinessManager and BusinessStaff to update shipment information, including shipment details, delivery status, and quantity validation. Ensures synchronization of shipment items and prevents over-shipment for each order item.
---
- Add `ShipmentUpdateDto` and `ShipmentDetailUpdateDto` with full validation logic.
- Implement `Update()` method in `ShipmentService` with business rules and soft-delete logic for shipment details.
- Add controller action `UpdateShipmentAsync` with role-based access and claim validation.
- Extend repository method `GetDeliveredQuantityByOrderItemId` to support excluding current shipment.
- Refactor Mapper: `MapToUpdatedShipment()` for Shipment entity update.
---
- …

feat(shipment): implement Update Shipment API with validation, quantity checks, and detail sync

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Refactor the processing batch creation logic to:
- Validate using `CropSeasonDetail` instead of `PlanDetail`
- Calculate remaining quantity based on `ActualYield`  
This improves accuracy and aligns with the farmer workflow (`Nông hộ` role).
---
- Replaced `PlanDetail`-based validation with `CropSeasonDetail`-based logic
- Used `ActualYield` for remaining quantity calculation
- Applied nested includes: `CropSeasonDetail → CommitmentDetail → PlanDetail/Commitment`
- Removed legacy `InputUnit` from DTO and logic
---
- `ProcessingBatchesController.cs`
- `ProcessingBatchCreateDto.cs`
- `IProcessingBatchService.cs`
- `ProcessingBatchMapper.cs`
---
- *(None)*
---
1. **Login** with role `Farmer` and retrieve JWT token  
2. Call endpoint:

refactor(processing-batch): validate using CropSeasonDetail and calculate by ActualYield

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ExpertAdvicesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/GeneralFarmerReportsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ExpertAdviceDTOs/ExpertAdviceCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ExpertAdviceDTOs/ExpertAdviceUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IAgriculturalExpertRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IExpertAdviceRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/AgriculturalExpertRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ExpertAdviceRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ExpertAdviceMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/GeneralFarmerReportService.cs

Chuẩn hóa logic xử lý trong `ExpertAdviceService` và cập nhật toàn bộ luồng phản hồi tư vấn chuyên gia từ phía nông dân và chuyên gia nông nghiệp. Hoàn thiện logic chuẩn theo Luồng 2 – Quản lý mùa vụ & tư vấn chuyên gia.
---
- Refactor `ExpertAdviceService` theo chuẩn: kiểm tra quyền từ `userId`, validate nghiệp vụ, reload entity sau tạo/sửa, trả về `ServiceResult`.
- Thêm DTO mới: `ExpertAdviceCreateDto`, `ExpertAdviceUpdateDto` dùng cho tạo và cập nhật.
- Cập nhật `ExpertAdviceMapper` để mapping giữa entity và các DTO mới.
- Bổ sung logic xử lý trong `GeneralFarmerReportService` và `GeneralFarmerReportsController` để gắn kết giữa báo cáo sự cố và phản hồi chuyên gia.
- Sửa `ExpertAdvicesController` theo chuẩn mới.
- Cập nhật repository interface và implementation:
- …

refactor(expert-advice): standardize service & controller logic

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractItemService.cs

Ensure that the frontend can successfully **create and update contracts**, including contract items. This fix targets **BusinessManager flows** and resolves validation & mapping issues between DTOs and domain models.
---
- Fixed `ContractItemCreateDto` to remove `ContractId` requirement for creation
- Adjusted mapping logic in `ContractMapper` and `ContractItemMapper` to support nested `ContractItems`
- Updated `ContractItemService` to correctly associate items during update
- Improved validation flow to prevent backend 400 errors on FE submission
---
- `ContractItemCreateDto.cs`
- `ContractViewDetailsDto.cs`
- `ContractItemMapper.cs`
---
- _N/A_
---
1. **Login** as `BusinessManager` to get JWT token
2. Test endpoints:
- `POST …

fix(contract): allow FE to create & update contract successfully by adjusting mappers, DTOs, and service logic

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/MediaController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/UploadImageController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Program.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/MediaDTOs/MediaFileResponse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/MediaDTOs/MediaUploadRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/MediaDTOs/UploadImageResult.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchDTOs/ProcessingBatchDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressCreateRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressResponse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressWithWastesDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingWastesDTOs/ProcessingWasteViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DakLakCoffeeSupplyChain.Common.csproj
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IMediaFileRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/MediaFileRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IMediaService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IUploadService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchWasteMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/MediaService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UploadService.cs

Add support for uploading multiple images and videos when creating a processing batch progress (`ProcessingBatchProgress`). After upload, update the `PhotoUrl` and `VideoUrl` fields in the progress entity. This applies to roles like `Farmer`, `Admin`, and `BusinessManager`.
---
- Implemented `UpdateMediaUrlsAsync(Guid progressId, string? photoUrl, string? videoUrl)` in `ProcessingBatchProgressService`
- Updated `CreateWithMedia` controller method to call `UpdateMediaUrlsAsync` after successful media upload
- Extracted the first image/video `MediaUrl` from the uploaded list
- Fixed `RelatedEntity` mismatch with `CHECK` constraint in the `MediaFiles` table
---
- …

"feat(progress): implement UpdateMediaUrlsAsync to update photo and video URLs after media upload"

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ShipmentDetailsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IShipmentDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentDetailService.cs

This PR enhances the security and correctness of the `ShipmentDetail` update flow by enforcing scoped permission based on the authenticated user. It ensures only authorized managers or their staff can update shipment details tied to contracts they own.
---
- Refactor `ShipmentDetailService.Update()` to accept `userId` from JWT claims
- Validate that the updating user is either a `BusinessManager` or managed `BusinessStaff`
- Verify access to related `Contract` by comparing `SellerId` with `managerId`
- Prevent changing `OrderItemId` after creation to ensure data integrity
- Return proper error messages based on validation failures
---
---
---
1. **Login** with a valid …

refactor(shipment-detail): enforce scoped update with userId claims, seller validation, and OrderItem immutability

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewAllAvailableDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentsDetailsDTOs/FarmingCommitmentsDetailsViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/FarmingCommitmentEnums/FarmingCommitmentStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CultivationRegistrationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

- Add additional business-related fields to the Farming Commitment and Cultivation Registration DTOs to better support frontend and API requirements.
- Correct the incorrect or inconsistent naming in the Details DTO to align with domain terminology and improve clarity.
- Ensure the new fields are properly mapped in both DTOs and the underlying entity models.
- Maintain data consistency and compatibility with existing API responses.
- Update serialization and deserialization logic to handle the new fields accurately.
- Enhance DTO validation to cover newly added business fields.
- Improve maintainability and extensibility of DTOs for future business requirements.

refactor(farming commitment dto, cultivation registration dto) Add some business field for dtos and fix details dto wrong name

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryBatchCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryBatchUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryItem/ContractDeliveryItemUpdateDto.cs

Improve readability and consistency across `ContractDeliveryBatch` and `ContractDeliveryItem` DTOs by reformatting and aligning field declarations, indentation, and comments.
---
- Reformatted `ContractDeliveryBatchCreateDto` and `UpdateDto` for consistent structure
- Adjusted `ContractDeliveryItemUpdateDto` spacing and layout for clarity
- Ensured alignment across all related DTOs for easier maintenance and team readability
---
- `ContractDeliveryBatchCreateDto.cs`
- `ContractDeliveryBatchUpdateDto.cs`
- `ContractDeliveryItemUpdateDto.cs`
---
- ❌ *(No new files added)*
---
> No functional/backend logic changed  
1. ✅ Ensure the solution builds successfully (`Ctrl + Shift + B` in VS)  
2. ✅ Check Swagger still renders APIs using affected DTOs  
3. ✅ No warnings or compiler errors from …

style(dto): format ContractDeliveryBatchCreateDto, UpdateDto, and DeliveryItemUpdateDto for readability

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/DBContext/DakLakCoffee_SCMContext.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessBuyerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessManagerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractDeliveryItemMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/UserAccountMapper.cs

Refactor and format multiple DTOs, mapper classes, and the database context to improve code readability and maintain a consistent coding style across the backend.
---
- Applied consistent indentation, spacing, and alignment to DTO and mapper classes.
- Reformatted `DakLakCoffee_SCMContext` for better structure and readability.
- Ensured mapper methods follow a uniform layout for easier maintenance.
- No business logic changes, purely formatting.
---
- `ProductUpdateDto.cs`
- `DakLakCoffee_SCMContext.cs`
- `BusinessBuyerMapper.cs`
- `BusinessManagerMapper.cs`
- `ContractDeliveryBatchMapper.cs`
- `ContractDeliveryItemMapper.cs`
- `RoleMapper.cs`
- `UserAccountMapper.cs`
---
- *None*
---
1. Run the project and ensure it builds successfully with no warnings.
2. Verify …

style(mapper, dto, dbcontext): format for readability and consistency

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmingCommitmentController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewAllAvailableDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/FarmingCommitmentEnums/FarmingCommitmentStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CultivationRegistrationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CultivationRegistrationService.cs

- Refactor the DTO used by the View Detail Cultivation Registration API to improve structure, clarity, and consistency.
- Ensure the DTO accurately represents all necessary fields related to cultivation registration details.
- Correct any naming inconsistencies or mismatches with domain terminology to enhance code readability.
- Align the DTO with updated entity models and other related DTOs for consistency across the system.
- Optimize serialization and deserialization processes for efficient data transfer.
- Enhance validation within the DTO to ensure data integrity and completeness.
- Maintain backward compatibility with existing API consumers while implementing improvements.
- Prepare the DTO for easier future maintenance and potential extensibility.

refactor(cultivation registration) Refactor dto of View detail Cultivation registration API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractItemDTOs/ContractItemUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/OrderDTOs/OrderItemDTOs/OrderItemUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProductDTOs/ProductUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Base/IGenericRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs

Improve code readability and maintain consistency across multiple DTO and repository files without changing business logic.
---
- Formatted `Contract`, `Order`, and `Product` DTO files for consistent indentation, spacing, and alignment.
- Cleaned up `IGenericRepository` interface formatting for better readability.
- Applied consistent style in `UnitOfWork` class.
---
- `ContractCreateDto.cs`
- `ContractUpdateDto.cs`
- `ContractItemCreateDto.cs`
- `ContractItemUpdateDto.cs`
- `OrderItemCreateDto.cs`
- `OrderItemUpdateDto.cs`
- `ProductCreateDto.cs`
- `ProductUpdateDto.cs`
- `IGenericRepository.cs`
- `UnitOfWork.cs`
---
- *No new files added.*
---
1. Review code in the affected files to ensure only formatting changes were made.
2. Build the solution to confirm no compilation errors.
3. Run …

style(dto, repository): format Contract, Order, Product DTOs and repository classes for readability

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonDetailController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropProgressDTOs/CropProgressCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropProgressDTOs/CropProgressUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/CropSeasonEnums/CropDetailStatus .cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/CropSeasonEnums/CropSeasonEnums.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ICropStageRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CropStageRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropSeasonDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropStageService.cs

Refactor và tối ưu hóa toàn bộ logic liên quan đến Crop Season và Crop Progress, bao gồm DTO, enum, mapper, service, và repository.  
Mục tiêu là chuẩn hóa quy trình xử lý dữ liệu, cải thiện khả năng bảo trì và hỗ trợ các tính năng mở rộng trong tương lai.
---
- Cập nhật **DTO** cho CropProgress (create/update) để đồng bộ dữ liệu đầu vào/đầu ra.
- Chỉnh sửa **CropDetailStatus** và **CropSeasonEnums** để rõ ràng hơn trong phân loại trạng thái.
- Refactor logic service cho **CropSeasonDetailService**, **CropProgressService**, **CropStageService**.
- Cải thiện repository interfaces và implementations cho **CropStage**.
- Cập nhật **CropProgressMapper** để hỗ trợ mapping mới.
- Đồng bộ controller **CropSeasonDetailController** với thay đổi từ service và DTO.
---
- …

Refactor and update Crop Season & Crop Progress modules

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmingCommitmentController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentUpdateStatusDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentsDetailsDTOs/FarmingCommitmentsDetailsUpdateStatusDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Enum/FarmingCommitmentEnums/FarmingCommitmentStatus.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IFarmingCommitmentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs

- Implement the Update Farming Commitment Status API to enable modification of the status of existing farming commitments.
- Support updating the `status` field with proper validation of allowed status values to ensure business rules compliance.
- Handle state transitions carefully to prevent invalid or inconsistent status changes.
- Provide clear and consistent API responses, including success confirmations and detailed error messages for failure cases.
- Ensure the API interacts correctly with the underlying data models and persists status updates reliably.
- Maintain backward compatibility with existing clients while incorporating the new update capability.
- Improve performance, reliability, and security for status update operations.
- Add necessary logging or auditing to track status …

feat(Farming commitment) Implement Update Farming commitment status API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropStageDTOs/CropStageCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropProgressMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropStageService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

fix crop-stage

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/NotificationsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IAgriculturalExpertRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IGeneralFarmerReportRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ISystemNotificationRecipientRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/ISystemNotificationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/AgriculturalExpertRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/GeneralFarmerReportRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/SystemNotificationRecipientRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/SystemNotificationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/INotificationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/GeneralFarmerReportService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/NotificationService.cs

feat: add notification system for ExpertAdvice module

---

Database/DakLakCoffee_SCM.sql
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ViewDetailsDtos/ProcurementPlanDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcurementPlanDTOs/ViewDetailsDtos/ProcurementPlanDetailsUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Generators/CodeGenerator.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcurementPlanMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

- Identify and fix issues in the Procurement Plan DTOs that are causing them to malfunction or not work as expected.
- Review the structure, field names, and data types in the DTOs to ensure they align with the backend entities and API contracts.
- Correct any mismatches or omissions in the DTO properties that could lead to serialization/deserialization errors or data inconsistencies.
- Ensure that nested or related objects within the Procurement Plan DTOs are properly defined and mapped.
- Enhance validation rules in the DTOs to catch invalid or missing data early.
- Test the updated DTOs thoroughly with various API calls to confirm they work correctly across different scenarios.
- Maintain backward compatibility by carefully handling renamed or removed fields, possibly using deprecated …

refactor(Procurement plan) Fix some dto of procurement plan not working

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ExpertAdvicesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/GeneralFarmerReportsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ExpertAdviceDTOs/ExpertAdviceViewForManagerDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/GeneralFarmerReportDTOs/GeneralFarmerReportViewForManagerDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/GeneralFarmerReportRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IGeneralFarmerReportService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/GeneralFarmerReportService.cs

feat: Add Business Manager endpoints for farmer reports and expert adviceMinh

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseOutboundReceiptDTOs/WarehouseOutboundReceiptCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseOutboundReceiptMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseInboundRequestService.cs

feat(outbound-receipt):update add destinationnote

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat Farminh

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Requests/ProcessingBatchProgressReques/AdvanceProcessingBatchProgressRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchEvalutionDTOs/EvaluationViewDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/AdvanceProcessingBatchProgressDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressCreateRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingBatchsProgressDTOs/ProcessingBatchProgressWithWastesDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/EvaluationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/EvaluationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

feat: Implement evaluation workflow and progress update after failed evaluation

---

Database/DakLakCoffee_SCM.sql

Align new **Shipment** records with the correct business workflow by setting the **default status to `Pending`** (previously `Delivered`) at insert time. This ensures shipments start in a not-yet-delivered state and move through the lifecycle properly.
---
- Update SQL script to set **default insert status = `Pending`** for `Shipments`.
- Keep other status values and transitions unchanged; only the **default on insert** is modified.
- No API contract changes; behavior changes only when `Status` is omitted at creation.
---
---
- _N/A_
---
1. **Login** with a suitable role (e.g., `BusinessManager` or `DeliveryStaff`) to obtain a JWT.
2. Create a shipment **without** specifying `Status`:
- `POST /api/shipments`
- Headers: `Authorization: Bearer {token}`
- …

feat(status): set default insert status to 'Pending' for Shipment (was 'Delivered') in DakLakCoffee_SCM.sql

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropSeasonsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/CropSeasonRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropSeasonService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

perf: optimize CropSeason service and API performance

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDTOs/ContractUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs

Enable support for uploading images or files (e.g., PDF, DOCX) when **updating a Contract**.  
This improves flexibility for Business Managers and Admins to attach related documents directly during contract updates.
---
- Implemented file/image upload handling in **ContractsController** (`PUT /contracts/{id}`)
- Updated **ContractUpdateDto** to accept `IFormFile` for images/files
- Extended **ContractService** to process uploads and map to Cloudinary storage
- Adjusted mappings and validation to ensure compatibility with existing contract update logic
---
- `ContractUpdateDto.cs`
- `ContractCreateDto.cs`
---
- None (reused existing upload helper/service from contract create flow)
---
1. **Login** as a `BusinessManager` to retrieve a valid …

feat(contract-upload): support file/image upload in contract update (Controller, DTOs, Service)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ContractDeliveryBatchDTOs/ContractDeliveryItem/ContractDeliveryItemUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IContractDeliveryItemRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ContractDeliveryItemRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractService.cs

Enforce delivery-batch quantity rules for **create/update** of `ContractDeliveryItem` and **auto-mark** a `ContractDeliveryBatch` as **Fulfilled** when the **sum of delivered quantities** reaches the **batch’s planned total**. Strengthens data integrity for BusinessManager/BusinessStaff flows.
---
- **Repository helpers (batch-level aggregations)**
- `SumPlannedQuantityByBatchAsync(Guid deliveryBatchId)`
- `SumPlannedQuantityByBatchAsync(Guid deliveryBatchId, Guid excludeDeliveryItemId)`
- `SumFulfilledQuantityByBatchAsync(Guid deliveryBatchId)`
- **DTO validation** (`ContractDeliveryItemUpdateDto`)
- `FulfilledQuantity >= 0`
- `FulfilledQuantity <= PlannedQuantity`
- **Service (Create/Update)**
- Enforce `Σ planned (batch) ≤ DeliveryBatch.TotalPlannedQuantity`  
↳ exclude current item on …

feat(contract-delivery-item): batch totals & auto-fulfill

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs

- Refactor the Update Status Farming Commitment API to include updating the `progressPercentage` fields in both the associated Plan and Plan Detail entities.
- Implement logic to recalculate and update `progressPercentage` based on the current status and relevant data from the farming commitment.
- Ensure that updates to `progressPercentage` are consistent, accurate, and reflect the true progress of the plan and its details.
- Handle database transactions properly to maintain data integrity when updating multiple related entities simultaneously.
- Validate input data and handle edge cases where progress might need to be reset, capped, or adjusted.
- Provide clear API responses reflecting the updated progress status and success or failure of the operation.
- Update service layers and data …

refactor(Farming commitment) Add update plan and plan detail progressPercentage in update status Farming commitment API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ExpertAdvicesController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ExpertAdviceDTOs/ExpertAdviceCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ExpertAdviceService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/MediaService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/UploadService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat: Add file upload support for ExpertAdvice

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/InventoryMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(role4): update logic name for inventory

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseOutboundReceiptMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseReceiptMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryLogService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(inventory-log):improve mapper to see who updated inventory

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmingCommitmentDTOs/FarmingCommitmentViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmingCommitmentMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmingCommitmentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

refactor cropseason

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseInboundRequestsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IWarehouseInboundRequestRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseInboundRequestRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IWarehouseInboundRequestService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseInboundRequestService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(inbound-request):update logic for inbound request

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseInboundRequestService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(inbound-request): fix logic

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/WarehouseOutboundRequestsController.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(outbound): fix logic fallback error

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/AgriculturalExpertsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AgriculturalExpertDTOs/AgriculturalExpertVerifyDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IAgriculturalExpertService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/AgriculturalExpertService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat: Add expert verification functionality

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/FarmerController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmerDTOs/FarmerVerifyDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/FarmerDTOs/FarmerViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IFarmerService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/FarmerMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/FarmerService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

"feat: Add verify functionality for Farmers management

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/InventoryDTOs/InventoryDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/InventoryRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/OrderRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ShipmentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/InventoryMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryService.cs

Enhance **Inventory detail response** to provide more comprehensive information for downstream features (e.g., reporting, shipment validation, quality control).  
Added `farm`, `location`, `result`, and `totalScore` to improve visibility of coffee stock data.
---
- Extended **InventoryDetailDto** with new fields (`Farm`, `Location`, `Result`, `TotalScore`).
- Updated **InventoryRepository** to fetch and join related data.
- Adjusted **InventoryService** and **InventoryMapper** to map new fields properly.
- Minor alignment changes in **OrderRepository** and **ShipmentRepository** for consistent data queries.
---
- `InventoryDetailDto.cs`
- `InventoryRepository.cs`
- `OrderRepository.cs`
- `ShipmentRepository.cs`
- `InventoryMapper.cs`
- `InventoryService.cs`
---
- No new files, only …

feat(inventory): include farm, location, result & totalScore in InventoryDetailDto and repository/service mappings

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CultivationRegistrationController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CultivationRegistrationDTOs/CultivationRegistrationViewSumaryDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICultivationRegistrationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CultivationRegistrationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CultivationRegistrationService.cs

- Implement the "Get by User Cultivation Registration" API to retrieve cultivation registration records specific to a given user.
- Design the API endpoint to accept user identification parameters (e.g., user ID or authentication token) securely.
- Ensure the API returns relevant cultivation registration details such as registration ID, status, quantities, dates, and other pertinent information for the user.
- Support filtering, sorting, and pagination if the user has multiple registrations to enhance performance and usability.
- Implement proper authorization and authentication checks to ensure users can access only their own registrations.
- Provide clear and consistent API responses with appropriate status codes and error handling.
- Write unit and integration tests to validate the …

Implement(Cultivation registration) Implement Get by user cultivation registration API

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

fix validation crop progress 

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Align the **Update Order** flow with **Create Order** by enforcing the same business validations (batch ownership, coffee type matching, and quantity limits) for BusinessManager/BusinessStaff.
---
- Validate **CDI belongs to the order’s DeliveryBatch** on update.
- Enforce **CoffeeType** match between `ContractItem` (via CDI → ContractItem) and `Product`.
- Check per-line and aggregated quantities:
- `requested ≤ (PlannedQuantity − FulfilledQuantity)` (clamped to 0).
- `requested ≤ Product.QuantityAvailable`.
- Block zero/negative quantities and missing references (CDI/Product/ContractItem).
- Batch-load related data with `Include(...ThenInclude(...))` to reduce DB round-trips.
- Keep friendly error messages using `ProductName` / `CoffeeType.TypeName`, fallback to IDs.
- Recompute …

feat(order): add Update validations (CDI in batch, CoffeeType match, qty ≤ planned−fulfilled & stock)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Enhance the **Shipment UpdateStatus** logic to prevent mobile app failures by adding validation checks and robust error handling for notification and database operations.  
This ensures smoother status updates and clearer error messages for end users (e.g., DeliveryStaff).
---
- Added validation checks before updating Shipment and related Order:
- Ensure `shipment.Order` exists
- Ensure `shipment.Order.DeliveryBatch` and `Contract` exist
- Improved error handling for notifications:
- Wrapped notification in `try/catch`
- Logged detailed exception without interrupting main process
- Enhanced SaveChanges handling:
- Wrapped DB save in `try/catch`
- Logged message + stack trace for debugging
- Returned more descriptive error messages to mobile app
---
- `Services/ShipmentService.cs`
---
- …

fix(shipment): improve UpdateStatus with validation and robust error handling (notification & SaveChanges) to prevent mobile app failure

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/INotificationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/NotificationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ShipmentService.cs

Enable **Delivery Staff** to successfully update `Shipment` status.  
Automatically send a notification to **BusinessManager** when status changes, ensuring business oversight.
---
- Implemented status update logic for Delivery Staff in `ShipmentService`
- Integrated `INotificationService` to notify BusinessManager on status change
- Adjusted validation and flow handling to ensure successful update and persistence
- Refactored error handling to prevent silent failures during notification
---
- `NotificationService.cs`
- `INotificationService.cs`
---
- *No new files added*
---
1. **Login** as `DeliveryStaff` to obtain JWT token  
2. Send request to endpoint:  
- `PUT /api/shipments/{id}/status`  
- Header: `Authorization: Bearer {token}`  
3. Example body:
```json
{ …
```

fix(shipment): enable delivery staff UpdateStatus with BusinessManager notification

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/OrderService.cs

Ensure **Product.QuantityAvailable** is correctly maintained whenever an **Order** is created, updated, deleted, or soft-deleted.  
This prevents overbooking by reserving stock for one order and making the remaining stock visible for others.
---
- Implemented logic in `OrderService` to decrease `QuantityAvailable` on **Order Create**  
- Enhanced **Order Update** to:
- Return quantities from old items  
- Deduct quantities from new/updated items  
- Handle diffs for modified items  
- Added logic in **Order Delete** and **SoftDeleteOrderById** to restore product quantities  
- Refactored helper `UpdateProductQuantityAvailable` method to handle both increase/decrease cases  
- Fixed type mismatch (`double?` vs `decimal`) when calculating quantity differences  
---
- …

feat(order): recalc QuantityAvailable from item diffs on create/update; restore UpdateProductQuantityAvailable; handle double?/decimal? cast

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ContractDeliveryItemsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IContractDeliveryItemService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProductMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ContractDeliveryItemService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(test-oder):add new ui for oder multi choice product

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/AuthController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropSeasonDTOs/CropSeasonCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/GeneralFarmerReportDTOs/GeneralFarmerReportViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/GeneralFarmerReportMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

fix date cropseason create

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/InventoryController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IInventoryService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/InventoryService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(inventory): add GetAvailableForProduct API (InventoryController, InventoryService, IInventoryService)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/WarehouseOutboundReceiptDTOs/WarehouseOutboundReceiptDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/WarehouseOutboundReceiptRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/WarehouseOutboundReceiptMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/WarehouseOutboundReceiptService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(outbound-receipt): fix logic subtract inventory when confirm outbound receipt

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcurementPlansController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IPaymentConfigurationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/IRepositories/IPaymentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/PaymentConfigurationRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/PaymentRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/UnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/DakLakCoffeeSupplyChain.Services.csproj
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcurementPlanService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): add payment when create procurmentplan

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentConfigurationsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationDeleteDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentConfigurationService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/PaymentConfigurationMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/RoleMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentConfigurationService.cs

Add a new API that allows **Admin** to create `PaymentConfiguration` records.  
This supports configuring registration fees, monthly fees, or other payment rules for different roles (e.g., Farmer, BusinessManager).
---
- Implemented **Create API** in `PaymentConfigurationsController` (`POST /api/paymentconfigurations`).
- Added service logic to validate role existence and map from DTO to entity.
- Introduced `PaymentConfigurationCreateDto` with validation attributes.
- Extended `PaymentConfigurationMapper` to map from `CreateDto` → `PaymentConfiguration` entity.
- Added logic to re-fetch created entity with `Role` included to return `RoleName` in the response.
---
- `PaymentConfigurationsController.cs`
- `IPaymentConfigurationService.cs`
- `PaymentConfigurationService.cs`
- …

feat(payment-config): implement create API (Controller, Service, DTO, Mapper, validation)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsProgressController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingMethodController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingStageController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Const.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodDTOs/ProcessingMethodUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodStageDTOs/CreateProcessingStageDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/ProcessingMethodStageDTOs/ProcessingStageUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/ProcessingHelper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Repositories/ProcessingStageRepository.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingMethodService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingStageService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

fix progress

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/MockIpnRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/PaymentAmountResponse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/ProcessPaymentSuccessRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/VnPayCreateRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/VnPayCreateResponse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/WalletTopupVnPayRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): implement wallet for admin

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs

Provide an API that allows a **Farmer** to retrieve detailed information about a specific crop they own.  
This ensures data security so that each Farmer can only access their own crops.
---
- Implemented **GetById** endpoint in `CropsController` with role restriction `Farmer`.
- Added service method `GetById(Guid cropId, Guid userId)` in `CropService`.
- Introduced **CropViewDetailsDto** for detailed crop representation.
- Extended **CropMapper** to map `Crop` entity → `CropViewDetailsDto` (including enum `CropStatus` and navigation properties).
- Query includes `CreatedByNavigation.User` and `UpdatedByNavigation` for displaying farmer names.
---
- `CropsController.cs`
- `ICropService.cs`
- `CropService.cs`
- `CropMapper.cs`
---
- `CropViewDetailsDto.cs`
---
1. **Login** with role …

feat(crop): implement GetById API for Farmer (Controller, Service, DTO, Mapper)

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(vnpay): add logic real for vnpay using ngrok test local

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/Models/Crop.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropProgressService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonDetailService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(crops): add auto status to crops

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/VnPayCreateResponse.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/PaymentHelper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IProcurementPlanService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcurementPlanService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): using ngrok for real IPN

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): using real IPN for wallet when add money for wallet

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/ProcessingBatchsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Repositories/UnitOfWork/IUnitOfWork.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ContractMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/ProcessingBatchMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchService.cs

Refactor and improve `ProcessingBatch` workflow including controller, service, and mapping layers.  
Update `UnitOfWork` interface and adjust `ContractMapper` & `ProcessingBatchMapper` to align with new logic.
---
- Updated **ProcessingBatchsController** to handle revised service logic  
- Modified **ProcessingBatchService** with refactored methods and improved handling  
- Adjusted **IUnitOfWork** interface to support new service requirements  
- Refactored **ContractMapper** and **ProcessingBatchMapper** for consistent data mapping  
---
- `ProcessingBatchsController.cs`
- `IUnitOfWork.cs`
- `ProcessingBatchMapper.cs`
---
- *(None in this PR – only refactor and modifications)*
---
1. **Login** with a valid role (e.g., …

refactor(processing-batch): update controller, service, mappers and unit-of-work interface

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AgriculturalExpertDTOs/AgriculturalExpertViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/AgriculturalExpertDTOs/AgriculturalExpertViewDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/AgriculturalExpertService.cs

Improve code readability and maintainability by formatting `AgriculturalExpert` DTOs and service implementation.  
No business logic was changed – this PR is purely a code cleanup and refactor.
---
- Formatted **AgriculturalExpertViewAllDto** for consistent style  
- Formatted **AgriculturalExpertViewDetailDto** for better readability  
- Cleaned up code style in **AgriculturalExpertService**  
---
- `AgriculturalExpertViewAllDto.cs`  
- `AgriculturalExpertViewDetailDto.cs`  
- `AgriculturalExpertService.cs`  
---
- *(None – no new files were added in this PR)*
---
1. **Login** with a valid role (e.g., `Admin` or `BusinessManager`) to obtain JWT token  
2. Test any existing endpoints using `AgriculturalExpertService`, such as:  
- `GET /api/agriculturalexperts`  
- `GET …

refactor(agricultural-expert): format DTOs and service implementation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

:feat(payment): fix logic

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): using url form fe

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs

Reverts PhucLHSE/DakLakCoffeeSupplyChain_BE#618

Revert "feat(payment): using url form fe"

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(payment): fix logic Repayment after initial cancellation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentConfigurationsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentConfigurationDtos/PaymentConfigurationUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/PaymentConfigurationMapper.cs

Add new fields (`ConfigName`, `MinTons`, `MaxTons`) to **Create** and **Update** DTOs for PaymentConfiguration.  
Ensure mapper and controller logic support these fields consistently, improving validation and backend data integrity.
---
- Added `ConfigName`, `MinTons`, `MaxTons` to **PaymentConfigurationCreateDto** and **PaymentConfigurationUpdateDto**.  
- Implemented custom validation (`IValidatableObject`) to check:
- `MinTons` ≤ `MaxTons`  
- `EffectiveTo` ≥ `EffectiveFrom`  
- Updated **PaymentConfigurationMapper** to handle new fields in create/update flows.  
- Fixed naming consistency in **PaymentConfigurationsController** for update method.  
---
- `PaymentConfigurationCreateDto.cs`  
- `PaymentConfigurationUpdateDto.cs`  
- `PaymentConfigurationMapper.cs`  
- …

feat(payment-config): add ConfigName, MinTons, MaxTons fields to Create/Update DTOs and update mapper; fix controller naming consistency

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/BusinessStaffController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessStaffDTOs/BusinessStaffDetailDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/BusinessStaffDTOs/BusinessStaffListDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/BusinessStaffMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/BusinessStaffService.cs

Improve code readability and maintain consistency across the **BusinessStaff** module.  
No business logic changes were introduced, only formatting and style adjustments for controller, DTOs, mapper, and service.
---
- Reformatted **BusinessStaffController** to follow project conventions.  
- Updated **BusinessStaffDetailDto** and **BusinessStaffListDto** for consistent property style.  
- Reformatted **BusinessStaffMapper** methods to align with code style.  
- Applied consistent formatting in **BusinessStaffService** implementation.  
---
- `BusinessStaffController.cs`  
- `BusinessStaffDetailDto.cs`  
- `BusinessStaffListDto.cs`  
- `BusinessStaffMapper.cs`  
- `BusinessStaffService.cs`  
---
- None (only refactoring applied).  
---
1. Run existing BusinessStaff API endpoints:  
- `GET …

refactor(business-staff): format controller, DTOs, mapper, and service for consistency

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/PaymentsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/PaymentDTOs/RecreateWalletTopupRequest.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/IPaymentService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/PaymentService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

Update payment recreate-url

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewAllDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(Crops): Add Note field to Crop DTOs and update mapper

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropApproveDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropCreateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropRejectDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/IServices/ICropService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/MediaService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat: Implement crops management with admin approval system

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/Helpers/ProcessingHelper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/ProcessingBatchProgressService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(update after evaltuon

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Mappers/CropMapper.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropSeasonDetailService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat(cropseasondetail)  : check role manager

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.APIService/Controllers/CropsController.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropUpdateDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/CropDTOs/CropViewDetailsDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Common/DTOs/MediaDTOs/DocumentInfoDto.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs
Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/MediaService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat: Add update crops  upload support for crop creation

---

Source/DakLakCoffeeSupplyChainBE/DakLakCoffeeSupplyChain.Services/Services/CropService.cs

---
---
---
---
3. Body mẫu:
```json
{ …
```

feat: fix deploy
